### PR TITLE
Feature #223 phoenix protocol reader

### PR DESCRIPTION
**Pull request by MichaelStritt**
1. We could improve the logic
    - Interpret **parameters** for **xasl** structure variables
2. We could add specific PCASL parameters
    - An exemplary PCASL phoenix protocol is in the google drive document

Otherwise I think it seems fine to be merged 👍

### CODE REVIEW

**Comment by MichaelStritt** [comment]
Hey @jan-petr, I've read your e-mail and added the additional parameters with 4ebfd3a. 👍 

Regarding the interpretation:
- **xAslulMode:** maybe we can get this one. The GSP table says that if this is 4, we should have Q2TIPS. In some other cases we have 2, but I'm not sure what technique was used there.
- alTI0 and alTI1: The GSP table uses these to assess if the dataset is a normal ASL or a PseudoM0. Maybe we can use this to find out if we have an M0 scan? Maybe the **M0Mode** will help here, too?

I'm moving the code to the Functions folder now.

**Review by jan-petr — CHANGES_REQUESTED** [review]
Looks very good. Some minor changes to do:

- Explain in the header what is the alternative to bUseDCMTK - i.e. Python
- Why is the phoenixProtocol output a cell and not a string?
- I already perform the reading of the Phoenix in my import. It would be thus good to split the reading itself and the parsing of the protocol to two independent functions. I mean that you can read+parse in a single function, but I need the parsing also separately.
- Please be more verbose in the description of the function so that the inputs/outputs/function is more clear.

Smart to have the ASL and 'raw parameter' output - I guess there's still a plenty of work ahead of us.

**Comment by MichaelStritt** [comment]
Hey @jan-petr, I tried to fix as much as possible in e27e33e.

> Explain in the header what is the alternative to bUseDCMTK - i.e. Python

> Please be more verbose in the description of the function so that the inputs/outputs/function is more clear.

The header description should be a bit better now.

> Why is the phoenixProtocol output a cell and not a string?

In Matlab I personally find it easier to work with cell arrays. I added a separate raw output now 👍 

> I already perform the reading of the Phoenix in my import. It would be thus good to split the reading itself and the parsing of the protocol to two independent functions. I mean that you can read+parse in a single function, but I need the parsing also separately.

Are you thinking of a separate script or just a separate function? I implemented a separate function, but I'd be happy to change it if you were thinking of something else.

**Review by jan-petr — APPROVED** [review]
OK

**Pull request merged**
