### PR TITLE
Closes #892 ExploreASL_Initialize: rm paths before addpath

### LINKED ISSUE #892: Existing toolbox Matlab paths conflict with ExploreASL toolboxes
### Description

If ExploreASL contains a toolbox (e.g., SPM) that was already initialized — i.e., its Matlab path was already included — then there may be conflicts between the toolbox version within ExploreASL and the one that was pre-existing

### Requirements

The implemented solution is to first detect ExploreASL toolboxes that were already added to the Matlab path outside of ExploreASL — i.e., not within `ExploreASL/External`.

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Bugfix: detect and remove pre-existing toolbox paths that might conflict with toolboxes included in ExploreASL

### PR DESCRIPTION
**Pull request by HenkMutsaerts**
### Linked issue

Closes #892

### How to test

Required: if not defined in the linked issue, add a simple test description here

### Comments

Optional: add helpful comments for the reviewers here

### CODE REVIEW

**Review by jan-petr — APPROVED** [review]
OK

**Comment by MichaelStritt** [comment]
@jan-petr & @HenkMutsaerts: did some changes to reduce the crazy verbosity, I bet users would greatly complain about that. I also added a condition for matlab related toolboxes, because that leads to super annoying bugs otherwise.

**Review by MichaelStritt — APPROVED** [review]

**Comment by HenkMutsaerts** [comment]
> @jan-petr & @HenkMutsaerts: did some changes to reduce the crazy verbosity, I bet users would greatly complain about that. I also added a condition for matlab related toolboxes, because that leads to super annoying bugs otherwise.
> 
> Edit: please add the "how to test" section next time, we kind of agreed on this.

* Thanks, but we have to remove the Matlab toolbox condition. There are users having e.g., SPM in their matlab toolbox, this is what we want to remove from paths. This is why I had a filesep in front of the regular expressions, so it wouldn't detect `/alst` but it would detect `/lst`

* I disagree with the verbose mode, or we have to default it to true. Users should not have initialized other spm versions, cat12 versions, or lst versions, this should always give a warning. We could reduce the number of warnings to max 1 per toolbox.

**Comment by MichaelStritt** [comment]
> > @jan-petr & @HenkMutsaerts: did some changes to reduce the crazy verbosity, I bet users would greatly complain about that. I also added a condition for matlab related toolboxes, because that leads to super annoying bugs otherwise.
> > Edit: please add the "how to test" section next time, we kind of agreed on this.
> 
>     * Thanks, but we have to remove the Matlab toolbox condition. There are users having e.g., SPM in their matlab toolbox, this is what we want to remove from paths. This is why I had a filesep in front of the regular expressions, so it wouldn't detect `/alst` but it would detect `/lst`
> 
>     * We also have to remove the `version` related regex, why is this there? Again, this won't cause a warning if you have multiple ExploreASL or toolbox versions per se. This will only cause a warning if you have initialized (i.e., added to the Matlab path) multiple versions; which is actually what we want to rule out.
> 
>     * I disagree with the verbose mode, or we have to default it to true. Users should not have initialized other spm versions, cat12 versions, or lst versions, this should always give a warning. We could reduce the number of warnings to max 1 per toolbox.
> 
>     * Note that this isn't a feature, but a bug. Users that have ExploreASL-specific toolboxes installed also in `Matlab/Toolbox` — such as Wibeke had — will get strange errors when running SPM functions inside ExploreASL, related to the version differences between our SPM version and the version installed outside of ExploreASL

@HenkMutsaerts & @jan-petr: For me all of this is asking for trouble. I got a ton of warnings and some errors afterwards just during coding, because Matlab was complaining about missing paths. I definitely wouldn't merge it like this. If a user decides to put spm inside the internal matlab directory, something is wrong on their side on not in ExploreASL.

**Comment by HenkMutsaerts** [comment]
> > > @jan-petr & @HenkMutsaerts: did some changes to reduce the crazy verbosity, I bet users would greatly complain about that. I also added a condition for matlab related toolboxes, because that leads to super annoying bugs otherwise.
> > > Edit: please add the "how to test" section next time, we kind of agreed on this.
> > 
> > 
> > ```
> > * Thanks, but we have to remove the Matlab toolbox condition. There are users having e.g., SPM in their matlab toolbox, this is what we want to remove from paths. This is why I had a filesep in front of the regular expressions, so it wouldn't detect `/alst` but it would detect `/lst`
> > 
> > * We also have to remove the `version` related regex, why is this there? Again, this won't cause a warning if you have multiple ExploreASL or toolbox versions per se. This will only cause a warning if you have initialized (i.e., added to the Matlab path) multiple versions; which is actually what we want to rule out.
> > 
> > * I disagree with the verbose mode, or we have to default it to true. Users should not have initialized other spm versions, cat12 versions, or lst versions, this should always give a warning. We could reduce the number of warnings to max 1 per toolbox.
> > 
> > * Note that this isn't a feature, but a bug. Users that have ExploreASL-specific toolboxes installed also in `Matlab/Toolbox` — such as Wibeke had — will get strange errors when running SPM functions inside ExploreASL, related to the version differences between our SPM version and the version installed outside of ExploreASL
> > ```
> 
> @HenkMutsaerts & @jan-petr: For me all of this is asking for trouble. I got a ton of warnings and some errors afterwards just during coding, because Matlab was complaining about missing paths. I definitely wouldn't merge it like this. If a user decides to put spm inside the internal matlab directory, something is wrong on their side on not in ExploreASL.
> 
> Especially if multiple users share a license they get like 100 warnings every time they initialize. That's crazy. Maybe you don't see it on your side, but that's not tested properly.

OK then it needs to be made more stable, such that it will only throw away important paths. Or we can for now include only spm, that should be sufficient as CAT12 & LST are usually in spm paths, and fsl is dealt with separately. Let me add a change and can you test it then again Michael?

**Comment by MichaelStritt** [comment]
> 
> 
> > > > @jan-petr & @HenkMutsaerts: did some changes to reduce the crazy verbosity, I bet users would greatly complain about that. I also added a condition for matlab related toolboxes, because that leads to super annoying bugs otherwise.
> > > > Edit: please add the "how to test" section next time, we kind of agreed on this.
> > > 
> > > 
> > > ```
> > > * Thanks, but we have to remove the Matlab toolbox condition. There are users having e.g., SPM in their matlab toolbox, this is what we want to remove from paths. This is why I had a filesep in front of the regular expressions, so it wouldn't detect `/alst` but it would detect `/lst`
> > > 
> > > * We also have to remove the `version` related regex, why is this there? Again, this won't cause a warning if you have multiple ExploreASL or toolbox versions per se. This will only cause a warning if you have initialized (i.e., added to the Matlab path) multiple versions; which is actually what we want to rule out.
> > > 
> > > * I disagree with the verbose mode, or we have to default it to true. Users should not have initialized other spm versions, cat12 versions, or lst versions, this should always give a warning. We could reduce the number of warnings to max 1 per toolbox.
> > > 
> > > * Note that this isn't a feature, but a bug. Users that have ExploreASL-specific toolboxes installed also in `Matlab/Toolbox` — such as Wibeke had — will get strange errors when running SPM functions inside ExploreASL, related to the version differences between our SPM version and the version installed outside of ExploreASL
> > > ```
> > 
> > 
> > @HenkMutsaerts & @jan-petr: For me all of this is asking for trouble. I got a ton of warnings and some errors afterwards just during coding, because Matlab was complaining about missing paths. I definitely wouldn't merge it like this. If a user decides to put spm inside the internal matlab directory, something is wrong on their side on not in ExploreASL.
> > Especially if multiple users share a license they get like 100 warnings every time they initialize. That's crazy. Maybe you don't see it on your side, but that's not tested properly.
> 
> OK then it needs to be made more stable, such that it will only throw away important paths. Or we can for now include only spm, that should be sufficient as CAT12 & LST are usually in spm paths, and fsl is dealt with separately. Let me add a change and can you test it then again Michael?

Sure. I guess we should just change our general method. Instead of removing everything besides ExploreASL, we should remove only the things that could be troublesome, so all paths besides the ExploreASL ones that include our internal toolboxes. Meaning we only throw out other xASL, spm, bids-matlab, cat, and lst related paths, right?

**Comment by HenkMutsaerts** [comment]
> > > > > @jan-petr & @HenkMutsaerts: did some changes to reduce the crazy verbosity, I bet users would greatly complain about that. I also added a condition for matlab related toolboxes, because that leads to super annoying bugs otherwise.
> > > > > Edit: please add the "how to test" section next time, we kind of agreed on this.
> > > > 
> > > > 
> > > > ```
> > > > * Thanks, but we have to remove the Matlab toolbox condition. There are users having e.g., SPM in their matlab toolbox, this is what we want to remove from paths. This is why I had a filesep in front of the regular expressions, so it wouldn't detect `/alst` but it would detect `/lst`
> > > > 
> > > > * We also have to remove the `version` related regex, why is this there? Again, this won't cause a warning if you have multiple ExploreASL or toolbox versions per se. This will only cause a warning if you have initialized (i.e., added to the Matlab path) multiple versions; which is actually what we want to rule out.
> > > > 
> > > > * I disagree with the verbose mode, or we have to default it to true. Users should not have initialized other spm versions, cat12 versions, or lst versions, this should always give a warning. We could reduce the number of warnings to max 1 per toolbox.
> > > > 
> > > > * Note that this isn't a feature, but a bug. Users that have ExploreASL-specific toolboxes installed also in `Matlab/Toolbox` — such as Wibeke had — will get strange errors when running SPM functions inside ExploreASL, related to the version differences between our SPM version and the version installed outside of ExploreASL
> > > > ```
> > > 
> > > 
> > > @HenkMutsaerts & @jan-petr: For me all of this is asking for trouble. I got a ton of warnings and some errors afterwards just during coding, because Matlab was complaining about missing paths. I definitely wouldn't merge it like this. If a user decides to put spm inside the internal matlab directory, something is wrong on their side on not in ExploreASL.
> > > Especially if multiple users share a license they get like 100 warnings every time they initialize. That's crazy. Maybe you don't see it on your side, but that's not tested properly.
> > 
> > 
> > OK then it needs to be made more stable, such that it will only throw away important paths. Or we can for now include only spm, that should be sufficient as CAT12 & LST are usually in spm paths, and fsl is dealt with separately. Let me add a change and can you test it then again Michael?
> 
> Sure. I guess we should just change our general method. Instead of removing everything besides ExploreASL, we should remove only the things that could be troublesome, so all paths besides the ExploreASL ones that include our internal toolboxes. Meaning we only throw out other xASL, spm, bids-matlab, cat, and lst related paths, right?

But this was exactly what the script did. It searched for folders that contained these toolboxes and only removed those paths.

**Review by MichaelStritt — APPROVED** [review]

**Pull request merged**
