### PR TITLE
#930 xASL_Iteration: move logs

### PR DESCRIPTION
**Pull request by MichaelStritt**
### Linked issue

#930

### CODE REVIEW

**Comment by MichaelStritt** [comment]
# Test

## derivatives

image

### lock

image

### log

image

**Comment by MichaelStritt** [comment]
## derivatives

image

### lock

image

### log

image

**Review by HenkMutsaerts — CHANGES_REQUESTED** [review]
Only now I see the figure, very nice!

Can we at the same time make sure that the naming is the same throughout. I wouldn't add the 'sub-' as this should have been done in the conversion. I would just use <SUBJECT>, without changing them or interpreting them. 

Note that `xASL_module_ASL_012S4093_2` should be `xASL_module_ASL_012S4093_2_ASL_1` or `xASL_module_ASL_012S4093_2_ASL_2`. So for session modules it should be <SUBJECT>_<SESSION>.

In the future, we could move the file reports (Missing*.csv etc) there as well, but this will confuse the users. We shouldn't have too many small changes from version to version, or the users will get crazy. Let's add this to our wishlist for version 2.0 :)

**Comment by MichaelStritt** [comment]
@HenkMutsaerts: Should work with c7051c9. If a user defines `sub-[...]` as the subject id instead of `[...]` we would have `sub-sub-[...]` though. There's no way around it though, since you can't use regular expressions for the symbolic fields within xASL_Iteration. You could implement that later on, but that wouldn't be too clean either. I'd leave it as it is right now.

**Review by jan-petr — APPROVED** [review]
OK.

**Pull request merged**
