### PR TITLE
Closes #486 Add issue templates

### LINKED ISSUE #486: Add issue template
### Release Notes

Introduce document templates for GitHub QC Workflow

### PR DESCRIPTION
**Pull request by MichaelStritt**
Added the following issue template:

> ### Description
> 
> Required: insert bug or feature description here
> 
> ### Requirements
> 
> Optional: add bug or feature requirements here
> 
> ### How to test
> 
> Optional: insert description about how to test the code changes here
> 
> ### Release notes
> 
> Required: summarize the changes for the release notes here

### CODE REVIEW

**Review by jan-petr — CHANGES_REQUESTED** [review]
This is very good. But I don't get one thing - is this going to be evoked automatically when creating a new issue?

I would slightly change one thing:
Requirements -> conditions (because these are conditions under which this bug appears, right? Dataset, parameters, OS? If yes, we might add these examples.

**Comment by MichaelStritt** [comment]
> 
> 
> This is very good. But I don't get one thing - is this going to be evoked automatically when creating a new issue?
> 
> I would slightly change one thing:
> Requirements -> conditions (because these are conditions under which this bug appears, right? Dataset, parameters, OS? If yes, we might add these examples.

It's a bit simpler. It's just a markdown template and every time you create an issue, you can select to use these four titles and the corresponding descriptions. You can see an example [here](https://youtu.be/UPsCXqxxJUA?t=397).

**Comment by MichaelStritt** [comment]
I just wanted to give it a try and if everyone likes it, we can create separate ones for bugs/features/releases etc.

**Comment by MichaelStritt** [comment]
Normally you would write the false behavior, so something like "when does the bug appear" or "on which os" etc. in the **description**. The **requirements** would be something like "if I insert this argument, it shouldnt crash and I get this result". The **how to test** would be something like "run this `script` to see if the requirements are fulfilled".

**Comment by jan-petr** [comment]
> > This is very good. But I don't get one thing - is this going to be evoked automatically when creating a new issue?
> > I would slightly change one thing:
> > Requirements -> conditions (because these are conditions under which this bug appears, right? Dataset, parameters, OS? If yes, we might add these examples.
> 
> It's a bit simpler. It's just a markdown template and every time you create an issue, you can select to use these four titles and the corresponding descriptions. You can see an example [here](https://youtu.be/UPsCXqxxJUA?t=397).

So it does pop-up automatically (or I mean I call *that* behavior automatic :)). That's really awesome!

**Comment by jan-petr** [comment]
> I just wanted to give it a try and if everyone likes it, we can create separate ones for bugs/features/releases etc.

Yes - we need slightly different ones for each - feel free to suggest the 3-4 versions. I'm sure everyone *will* like that :)

**Comment by jan-petr** [comment]
> Normally you would write the false behavior, so something like "when does the bug appear" or "on which os" etc. in the **description**. The **requirements** would be something like "if I insert this argument, it shouldnt crash and I get this result". The **how to test** would be something like "run this `script` to see if the requirements are fulfilled".

Ah ok. Sounds good. But we might want to add a minimal example in each category, as I was a bit confused what each category means.

**Review by jan-petr — CHANGES_REQUESTED** [review]
This is very nice. I want all right now :)
Bug, release, feature would be the basic ones. Perhaps also documentation.

And you want to add HJ so that he modifies these right now before creating a new issue for that :)

**Comment by HenkMutsaerts** [comment]
@MichaelStritt very nice! I would only suggest to add one line, which will help us a lot as well :)

### Summary for CHANGES.md

Don't you agree @jan-petr ?

**Comment by jan-petr** [comment]
> @MichaelStritt very nice! I would only suggest to add one line, which will help us a lot as well :)
> 
> ### Summary for CHANGES.md
> Don't you agree @jan-petr ?

Yes - that's one of the main motivations. But 'Summary for CHANGES.md' == 'Release notes' - I like the second a bit more as it sounds more stylish ;) But I'm fine with both.

**Comment by jan-petr** [comment]
On a second thought. I do not have quick ideas on what to fill for different issue types. So if you do not have any idea either, we can merge right away and fill in later...

**Review by jan-petr — APPROVED** [review]
See my and HJ's comments. But feel free to merge at any time.

**Comment by MichaelStritt** [comment]
I'd merge this now and add a PR template in a separate issue 👍 
GitHub creates these branches and PRs automatically, so it's a bit easier this way.
I personally prefer **Release notes** compared to **Summary for changes.md**.

**Comment by jan-petr** [comment]
Agree! Please add release notes to this issue - in this case we probably only need to say that there are no release notes as this doesn't affect the code :)

**Pull request merged**
