### PR TITLE
Feature #112 output tc for asl2t1w

### LINKED ISSUE #112: Saving Tanimoto Coefficient of the final ASL-T1w registration
Will be saved as one of the QC parameters.
Henk: Name the structure and field for saving this.
Jan: Implement.

### PR DESCRIPTION
**Pull request by jan-petr**
* Writing the Tanimoto coefficient for ASL2T1 registration to the x-struct and to the QC output.
* QC Output is cleaned at the start of the ASL module and not only in the QC submodule.
* Saving TC as registration statistics in the Population module

Close #112

### CODE REVIEW

**Review by HenkMutsaerts — CHANGES_REQUESTED** [review]
## xASL_wrp_VisualQC_ASL.m
I would keep the cleaning here. Each submodule should load and save x.mat on its own.

## xASL_module_ASL
I would remove the cleaning of x.Output & x.Output_im. This will not work nicely if you do a rerun and skip certain submodules.

## xASL_stat_GetRegistrationStatistics
* Replace “CSV” to “TSV” throughout
* add comments (e.g. that you initialize with NaNs)
* Line 63: Here you load the QC_collection_<SUBJECT_ID>.json, and include all parameters, not only the TC fields? Perhaps it is easier to load the x.mat’s and insert any fields that include “TC”? E.g.:
if regexp(CurrentField, ‘^TC.*Perc$’

**Comment by jan-petr** [comment]
> ## xASL_wrp_VisualQC_ASL.m
> I would keep the cleaning here. Each submodule should load and save x.mat on its own.

After the Whatsapp discussion - the agreement is to keep it as it is now?
 
> ## xASL_module_ASL
> I would remove the cleaning of x.Output & x.Output_im. This will not work nicely if you do a rerun and skip certain submodules.

We need to clean it somewhere - keeping it on that line which had other cleaning stuff was the most reasonable to me. Do we keep it or change it?

> ## xASL_stat_GetRegistrationStatistics
> * Replace “CSV” to “TSV” throughout

Done.

> * add comments (e.g. that you initialize with NaNs)

Done.

> * Line 63: Here you load the QC_collection_<SUBJECT_ID>.json, and include all parameters, not only the TC fields? Perhaps it is easier to load the x.mat’s and insert any fields that include “TC”? E.g.:
>   if regexp(CurrentField, ‘^TC.*Perc$’

I can use x.mat instead of the QC.json. But I find that using QC.json is better and safer as that should include the final list of QC values and nothing else = a small file. While x.mat is a 1MB zipped file with a thousand of things. So the JSON is much better for extracting the same values.

I don't take all parameters but only those listed at line 38 (practice taken from the other xASL_stat_Get*.m from the Population module.

The regexp stuff won't work, because the list of fields to include might differ between subjects - so it would mess up the columns and we would have to create a dynamic list of columns and update at each step. This would make things much less flexible. So including a predefined fields is much easier for now.

**Comment by HenkMutsaerts** [comment]
## xASL_wrp_VisualQC_ASL & xASL_module_ASL
Yes, let's keep this for now. In the near future, we should revamp it in such a way that each submodule loads and saves.

## xASL_stat_GetRegistrationStatistics - use QC_*.json instead of x.mat
Good point. Currently, this is not yet completely proof, as the QC output of xASL_wrp_RegisterASL will be saved immediately to x.mat and only much later to QC*.json. So your solution is good, but would need a bypass altogether of the x.mat. So for QC: instead of loading & writing the x.mat, we should load & write the QC*.json, do you agree?

**Review by HenkMutsaerts — APPROVED** [review]
See comments above, if you agree, we can add these ideas as new issues, and merge this PR.

**Comment by jan-petr** [comment]
Yes, I agree, this has already an issue #121

I agree to write the QC*.json instead of the x.mat. That will make stuff much easier, as the changes in the x.mat are almost always thrown away after each submodule. 

There's only one question then - should this QC*.json loading and saving happen inside the submodule. Or should the submodule output a QC structure, which is then added to the QC*.json. I support the second option and I have wrote it like that to the #121 - can you please verify that there while we have it fresh in our heads, so that we reach an agreement that I can later implement?

**Comment by HenkMutsaerts** [comment]
>I agree to write the QC*.json instead of the x.mat. That will make stuff much easier, as the changes in the x.mat are almost always thrown away after each submodule.
Correction: the changes in x.mat are not thrown away, but the changes in x, right? At least that's the idea. Anyway, I agree changing QC*.json is more specific.
>There's only one question then - should this QC*.json loading and saving happen inside the submodule. Or should the submodule output a QC structure, which is then added to the QC*.json. I support the second option and I have wrote it like that to the #121 - can you please verify that there while we have it fresh in our heads, so that we reach an agreement that I can later implement?
I agree with you here. This should be standardized over all submodules.
Will merge this now!

**Pull request closed without merging**
