### PR TITLE
Docu #300 add martin, patricia, beatriz and change docu workflow

### PR DESCRIPTION
**Pull request by MichaelStritt**
@MDijsselhof: Just minor changes to add Martin and Patricia to the all contributors readme part.

### CODE REVIEW

**Review by jan-petr — CHANGES_REQUESTED** [review]
We can add Beatriz Padrela as well, while we are at it.

**Comment by MichaelStritt** [comment]
> We can add Beatriz Padrela as well, while we are at it.

Then she needs to be added to the GitHub Team first 👍 

Can you do this @HenkMutsaerts ?

**Comment by MichaelStritt** [comment]
@jan-petr: added Beatriz 👍

**Comment by MichaelStritt** [comment]
To avoid unncessary conflicts, I'll solve #345 here.

**Review by jan-petr — APPROVED** [review]
It looks all good.

**Pull request merged**
