### PR TITLE
Feature #35 b sup calculation

### PR DESCRIPTION
**Pull request by HenkMutsaerts**

### CODE REVIEW

**Comment by HenkMutsaerts** [comment]
For Yeva (Jan's MSc student) to test the background suppression correction without smoothing:

If you avoid adding `x.M0_conventionalProcessing` to your DataPar.m, `xASL_wrp_ProcessM0` will copy the standard space M0 after quantification but before masking/smoothing.

**Review by MichaelStritt — CHANGES_REQUESTED** [review]
Finally found some time to check this 👍 

The changes from **BackGrSupprPulses** to **BackgroundSuppressionNumberPulses** are really straight forward and seem to be fine to me :)

The changes in the **io_mTRIAL** header are not necessary. I removed this part from the header and the whole script is going to change as soon as we move to BIDS anyway. This just leads to a conflict right now.

Regarding the header in **xASL_quant_M0**:

I know you didn't change that much there, it's just that maybe we should write down which fields are added in the x struct. 
So some information in the _OUTPUT:_ part, besides that the x struct comes out, would be nice. Would make it easier for reviewers to test it, too.

Additionally, every xASL header need an _EXAMPLE:_ part. If we don't have an example we should just use `EXAMPLE: n/a.` This helps the **docu crawler.**

I manually tested **xASL_quant_M0** and especially **xASL_quant_RevertBsupFxControl**. I couldn't find/produce a nice test data set for it, but as far as I can see it right now, we don't get any errors :)

```
[M0IMtest] = xASL_quant_M0(M0IM, x);
x.M0_usesASLtiming didnt exist, set to 1, because of absence background suppression, same timing in mean control (used as M0) as in ASL
Warning: ...
x.Q.PresaturationTime is missing or empty, using default value
This assumes that a pre-saturation pulse has been played at the start of the sequence
For the average slice: Control image divided by 0.40875 to correct for background suppression
Using BackgroundSuppressionPulseTime=...
with presaturation time=..., tissue T1=...
And SliceReadoutTime= ...
This converts the control image to allow its use as a pseudo-M0 image
Background suppression pulses have saturated the pseudo-M0 signal, no need for correcting incomplete T1 relaxation
```

**Comment by jan-petr** [comment]
> Finally found some time to check this 

Thanks. Finally found some time to reply :)

> The changes in the **io_mTRIAL** header are not necessary. I removed this part from the header and the whole script is going to change as soon as we move to BIDS anyway. This just leads to a conflict right now.

OK. Reverted those so that I don't have to do conflict solving.
 
> Regarding the header in **xASL_quant_M0**:
> I know you didn't change that much there, it's just that maybe we should write down which fields are added in the x struct.
> So some information in the _OUTPUT:_ part, besides that the x struct comes out, would be nice. Would make it easier for reviewers to test it, too.

Very good point! Filled in all the info.
 
> Additionally, every xASL header need an _EXAMPLE:_ part. If we don't have an example we should just use `EXAMPLE: n/a.` This helps the **docu crawler.**

Thanks. Didn't know that. But in this case - which function is missing it?

> I manually tested **xASL_quant_M0** and especially **xASL_quant_RevertBsupFxControl**. I couldn't find/produce a nice test data set for it, but as far as I can see it right now, we don't get any errors :)

Thanks.

Final edit to do for Yeva is to make sure that BSup-M0 correction works with Background timings defined after the start of labeling before the readout (following the new BIDS definition) - I will make this change in the next commit.

**Comment by MichaelStritt** [comment]
> Thanks. Didn't know that. But in this case - which function is missing it?

I can quick fix this in develop if there are some problems right before the release. So this should be okay 👍 

> Very good point! Filled in all the info.

Thanks :) Let's merge!

**Review by MichaelStritt — APPROVED** [review]

**Pull request merged**
