### PR TITLE
Optimize #902 remove parfor

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

#902

### CODE REVIEW

**Comment by jan-petr** [comment]
Shall we remove code on line 182 as well?

**Review by MichaelStritt — APPROVED** [review]
👍

**Comment by MichaelStritt** [comment]
> Shall we remove code on line 182 as well?

Hm... not sure. Let's not change too much to keep everything stable before the release.

**Review by HenkMutsaerts — CHANGES_REQUESTED** [review]
Nice, what about the other two occurrences? Do we leave them in?

`cat_surf_epivolsurf`
`zspm_dcm_fit`

Nobody uses these, so safe to replace the `parfor` with `for` here to be sure Matlab never checks for this toolbox.

Then we can close the other issue as "duplicate".

**Comment by jan-petr** [comment]
> zspm_dcm_fit



> Nice, what about the other two occurrences? Do we leave them in?
> 
> `cat_surf_epivolsurf` `zspm_dcm_fit`
> 
> Nobody uses these, so safe to replace the `parfor` with `for` here to be sure Matlab never checks for this toolbox.

There it is already commented out. No need to remove.

> Then we can close the other issue as "duplicate".

Which other issue? #888 this is already closed...

**Review by HenkMutsaerts — APPROVED** [review]

**Pull request merged**
