### PR TITLE
Fixes #848 xASL_bids_BIDSifyAnatJSON: check parameter size, raise warning

### LINKED ISSUE #848: BIDSifyAnatJSON crashes because of RepTime array
### Description
For one of the TWINS datasets (EMI 301), there is an error in NII2BIDS. In xASL_bids_BIDSifyAnatJSON the code crashes because jsonOut.RepetitionTimePreparation is an array. We definitey need to check for that in the code and why that happens for this indiviudal dataset.

```matlab
	% If RepetitionTimePreparation is equal to RepetitionTime, then remove RepetitionTimePreparation
	if isfield(jsonIn,'RepetitionTime') && isfield(jsonIn,'RepetitionTimePreparation') &&...
			isnear(jsonIn.RepetitionTime,jsonIn.RepetitionTimePreparation)
		jsonOut = rmfield(jsonOut,'RepetitionTimePreparation');
	end
```

### Requirements

Optional: add bug requirements here

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Improve repetition time field checks and add a user warning.

### PR DESCRIPTION
**Pull request by MichaelStritt**
### Linked issue

Check out #848

### How to test

@BeatrizPadrela: please test this with the twins data

### Comments

Optional: add helpful comments for the reviewers here

### CODE REVIEW

**Comment by MichaelStritt** [comment]
@BeatrizPadrela: I assigned you, so if you think this is fine, move it to @jan-petr's bucket. If he agrees, he can move it back to your bucket and you can merge it yourself.

**Comment by BeatrizPadrela** [comment]
It works and gives no errors!!
Is it normal that it creates a folder for T1 and not for FLAIR? 
image

**Comment by MichaelStritt** [comment]
> It works and gives no errors!!
> Is it normal that it creates a folder for T1 and not for FLAIR?

@BeatrizPadrela: I think so. At least in temp. In derivatives we should have the normal ExploreASL legacy structure though. Can you approve the PR if you're fine with it? I already moved it to @jan-petr's bucket.

**Review by BeatrizPadrela — APPROVED** [review]
Ok!

**Review by jan-petr — APPROVED** [review]
OK. Please complete the "Release note" before merging.

**Pull request merged**
