### PR TITLE
Feature #131_GUIenhancements_set1

### PR DESCRIPTION
**Pull request by MauricePasternak**
Primary critique requested for this pull is the Importer functionality:

@HenkMutsaerts - whether you could verify that new submodule ("Folder Unpack" tab after opening the Importer) correctly unpacks a directory containing multiple information types (scan, subject, etc.) into distinct directory levels. Fair warning: directories that do not fit the pattern of the others (warnings are given in advance indicating which ones) will be removed after the backup copy is made and prior to the restructuring step. Should be multi-threaded and since I switched to python3.8, it leverages OS-specific file operations for slightly better performance. 

## BEFORE
Unpack - before
## AFTER
Unpack - after

@jan-petr - assuming "well-behaved" directory structure, whether you find the Importer functionality acceptable for both legacy and BIDS import. I believe I've correctly implemented your points on Philips and dcm2niix. Fair warning for the BIDS import: certain asl sidecar parameters that are usually not found in DICOM headers (i.e LabellingDuration) will be added at the ParmsMaker run step if it detects that the study is a BIDS imported study. So, if you plan to use the validator afterwards, please run both Importer and ParmsMaker modules.

You will find the compiled version for Windows up to date with this pull request in the google drive under ExploreASL_Compiled as ExploreASL_GUI_Winx64setup_version-0_2_1.zip

### CODE REVIEW

**Comment by HenkMutsaerts** [comment]
Looks great! I don't have time to test this unfortunately, I would focus first on the issues that Vera needed fixing so we can proceed to more clinical application testing. I know this was an issue as well, but this was fixable by wrapping around the ExploreASL_Import (avoiding opening a full can of worms) so I would focus first on the other issues (that we cannot fix within ExploreASL), is that OK with you?

Otherwise, I would ask Vera to test this. Did you receive her mail, she asked you if you have time this Thursday 14h00 (08h00 your time) to help her go through the GUI and perfect it for first clinical use 👍

**Comment by HenkMutsaerts** [comment]
@MauricePasternak Did Vera or Jan have time to test this, that it works satisfactory? I cannot read the Python files so can't conduct a proper review :)

**Comment by MauricePasternak** [comment]
I guided Vera through 3/4 modules. We did not have time to go in-depth into the graphing portion (and it featured a bug that has since been fixed: see 70f848c above).

But the real test is whether someone can go about using it without my guidance. To that end, most of the GUI other than the graphing module has hover-over tooltips explaining what each widget does or demands. Also, I think the GUI can now be installed

**Comment by MichaelStritt** [comment]
Hey, the PR is now open since more than a month. I thought I could help here and test the new functionalities, but we still use python 3.7 on the server and that's the only platform I have Matlab installed. This will change as soon as we can use the Matlab Runtime 👍 

Do we need to test this more extensively or can we do the merge? Just thought it would be a good idea not to forget this PR.

Help wanted @HenkMutsaerts and @jan-petr :)

**Comment by MauricePasternak** [comment]
The features you saw in today's meeting were pushed yesterday. I, personally, believe it is clear for a merge.

**Review by MichaelStritt — APPROVED** [review]
Looking good, let's merge

**Comment by MichaelStritt** [comment]
Hey @MauricePasternak 
I don't know why, but there were **a lot** of conflicts between your code in the `develop branch` and the `feature-#131 branch`.
I tried to resolve them as good as I can, but I don't know you're code as good as you do. Now the web interface let's you merge automatically. Tried my best but I'm not 100% sure if everything's correct now.
Can you have a look @jan-petr ?

**Comment by MauricePasternak** [comment]
That's strange. All my additions (other than editing gitignore to include venv-related names) should be solely restricted to the External/ExploreASL_GUI directory. If you encountered any conflicts outside of that, it is likely the result of the pull being left out for too long.

**Pull request merged**
