### PR TITLE
Fixes #860 xASL_imp_DCM2NII & NII2BIDS: fix behavior for multiple anat files

### LINKED ISSUE #860: Multiple anatomical files exported by DCM2NIIX
### Description

I think I found a weird T1 flavor or it's 2 images in one or something like that. It happens in the first session. It definitely finds ASL, FLAIR and T1w. Later on you get two NIfTIs from DCM2NIIX. For me that's not necessarily a big problem. I can probably just delete one of them. The problem is that ExploreASL doesn't give any warning whatsoever and in the end you only have the ASL in your derivatives. We should probably count the number of T1 niftis that come out of DCM2NIIX and then raise a warning if it's more then one?

image

image

### How to test

- Run the import on ADNI case 006_S_4485.
- Test that this doesn't crash other datasets with a subset of the flavor library

### Release notes

Handle multiple anatomical files exported by DCM2NIIX

### PR DESCRIPTION
**Pull request by MichaelStritt**
### Linked issue

#860

### CODE REVIEW

**Comment by MichaelStritt** [comment]
### Test with ADNI case

```
>> x = ExploreASL(pathTest,[1 1 0 1],0);
ExploreASL will run the import workflow and will load the dataset...
==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
Dataset Root        ...M:\SoftwareDevelopment\MATLAB\m.stritt\Process_ADNI_3\output\006_S_4485
Import Modules      DCM2NII NII2BIDS BIDS2LEGACY
Process Modules     
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.8.0 initialized ... 
================================== DICOM to NIFTI CONVERSION =================================

Matching files (#=6):
sub-006S4485\session_1_2018-09-25_10_53_15.0\ASL\S729782
sub-006S4485\session_1_2018-09-25_10_53_15.0\FLAIR\S729786
sub-006S4485\session_1_2018-09-25_10_53_15.0\T1w\S729784
sub-006S4485\session_2_2019-10-01_11_40_18.0\ASL\S914718
sub-006S4485\session_2_2019-10-01_11_40_18.0\FLAIR\S914722
sub-006S4485\session_2_2019-10-01_11_40_18.0\T1w\S914720

Running DCM2NIIX...

...

================================== NIFTI to BIDS CONVERSION ==================================
Checking dataset_description.json ...
Missing recommended fields:           HEDVersion


====================================== CONVERT SESSION =======================================
Converting subject 006S4485, session 1, run 1 ...
Multiple anatomical NIfTIs exported by DCM2NIIX, automatically selecting the first one...
Scan sub-006S4485_ses-1_T1w ...
Multiple anatomical NIfTIs exported by DCM2NIIX, automatically selecting the first one...
Scan sub-006S4485_ses-1_FLAIR ...
Scan sub-006S4485_ses-1_asl ...

...
```

image

**Comment by MichaelStritt** [comment]
## Minor flavor testing

I selected three flavors that have both ASL and T1w scans:

```json
"flavorList": ["GE_PCASL_3Dspiral_14.0LX_1", "Philips_PCASL_3DGRASE_5.4.0.2_1", "Siemens_PCASL_3DGRASE_VE11C_2"]
```

### BIDS conversion

```console
================================== CHECK THE BIDS CONVERSION =================================
Dataset: GE_PCASL_3Dspiral_14.0LX_1
Dataset: Philips_PCASL_3DGRASE_5.4.0.2_1
Dataset: Siemens_PCASL_3DGRASE_VE11C_2
```

### LEGACY conversion

```console
================================= CHECK THE LEGACY CONVERSION ================================
Dataset: GE_PCASL_3Dspiral_14.0LX_1
Dataset:   derivativesReference
Missing:   \ExploreASL\bidsReportASL.json
Missing:   \ExploreASL\import_summary.csv
Missing:   \ExploreASL\xASL_module_Import.log

Dataset: Philips_PCASL_3DGRASE_5.4.0.2_1
Dataset:   derivativesReference
Missing:   \ExploreASL\bidsReportASL.json
Missing:   \ExploreASL\import_summary.csv
Missing:   \ExploreASL\xASL_module_Import.log

Dataset: Siemens_PCASL_3DGRASE_VE11C_2
Dataset:   derivativesReference
Missing:   \ExploreASL\bidsReportASL.json
Missing:   \ExploreASL\import_summary.csv
Missing:   \ExploreASL\xASL_module_Import.log
```

The comparison part seems to be a bit bugged, it shouldn't show the report and log files, but this isn't the fault of the changes within this branch. From my POV everything seems fine.

**Comment by MichaelStritt** [comment]
@jan-petr: I'm not 100% sure if it's correct to just take the first one though. Maybe we have to merge them in some specific cases. For ADNI I'll probably just skip this session, since it's quite a lot of manual work to make it work for this rare case.

**Review by jan-petr — APPROVED** [review]
OK. Can you check for this particular case if there are any differences between the two files? Parameters, absolute signal value, motion, etc? It would be good to know if the acquisition was done twice with a slightly different results or parameters, or if it was only saved twice and is otherwise identical...

**Comment by MichaelStritt** [comment]
> 
> 
> OK. Can you check for this particular case if there are any differences between the two files? Parameters, absolute signal value, motion, etc? It would be good to know if the acquisition was done twice with a slightly different results or parameters, or if it was only saved twice and is otherwise identical...

I created a follow-up issue #866 and copied all the relevant text there.

**Pull request merged**
