### PR TITLE
Feature #166 adni import

### PR DESCRIPTION
**Pull request by MichaelStritt**
Works fine if you rename the visit folders

Example:
- ASL/2015-01-01/SXXXX => ASL/2015-01-01/01
- ASL/2016-01-01/SXXXX => ASL/2016-01-01/02

### CODE REVIEW

**Comment by HenkMutsaerts** [comment]
* Nice work!
* Does ADNI have 7 visits already?
* You use the brackets () that are reserved for token definition also to find different variations of the scan type names, does his work, or do you need help from me here?
* Note that you don't have to include the full file or foldername in your token, e.g. : 
  * instead of `(Axial_T2-FLAIR.*)` you could do `.*(FLAIR).*`
  * instead of `'^(Axial_T2-FLAIR.*)|^(Sagittal_3D_FLAIR.*)|^(AX_T2_FLAIR_NO_ANGLE.*)'` you could do `'^.*(FLAIR).*$'`
* Why do you specify the beginning `^` but not the ending `$` in the regular expressions? You can of course google for `regular expression cheat sheet` if you need to check the meanings of all these. There are a few differences in the way ExploreASL_Import uses them, mainly the brackets ().

**Review by HenkMutsaerts — APPROVED** [review]
* Nice work!
* Does ADNI have 7 visits already?
* You use the brackets () that are reserved for token definition also to find different variations of the scan type names, does his work, or do you need help from me here?
* Note that you don't have to include the full file or foldername in your token, e.g. : 
  * instead of `(Axial_T2-FLAIR.*)` you could do `.*(FLAIR).*`
  * instead of `'^(Axial_T2-FLAIR.*)|^(Sagittal_3D_FLAIR.*)|^(AX_T2_FLAIR_NO_ANGLE.*)'` you could do `'^.*(FLAIR).*$'`
* Why do you specify the beginning `^` but not the ending `$` in the regular expressions? You can of course google for `regular expression cheat sheet` if you need to check the meanings of all these. There are a few differences in the way ExploreASL_Import uses them, mainly the brackets ().

**Comment by HenkMutsaerts** [comment]
* Nice work!
* Does ADNI have 7 visits already?
* You use the brackets () that are reserved for token definition also to find different variations of the scan type names, does his work, or do you need help from me here?
* Note that you don't have to include the full file or foldername in your token, e.g. : 
  * instead of `(Axial_T2-FLAIR.*)` you could do `.*(FLAIR).*`
  * instead of `'^(Axial_T2-FLAIR.*)|^(Sagittal_3D_FLAIR.*)|^(AX_T2_FLAIR_NO_ANGLE.*)'` you could do `'^.*(FLAIR).*$'`
* Why do you specify the beginning `^` but not the ending `$` in the regular expressions? You can of course google for `regular expression cheat sheet` if you need to check the meanings of all these. There are a few differences in the way ExploreASL_Import uses them, mainly the brackets ().

**Comment by MichaelStritt** [comment]
Hey Henk, thanks for the feedback. I'm implementing it right away 👍 
> - instead of (Axial_T2-FLAIR.*) you could do .*(FLAIR).*
> - instead of '^(Axial_T2-FLAIR.*)|^(Sagittal_3D_FLAIR.*)|^(AX_T2_FLAIR_NO_ANGLE.*)' you could do '^.*(FLAIR).*$'

**Pull request merged**
