### PR TITLE
#1415 Fix PeRev directions

### LINKED ISSUE #1415: Identify PERev directions correctly
### Description

Once PERev M0 with inverted phase-encoding direction is found it assigns it automatically j and j- directions and calls in AP-PA. But sometimes, we have i an i- and LR and RL directions!!!

### Tasks

- [x] If directions are known from the DICOM, then don't change them.
- [x] If directions are j and j- - call it AP-PA, otherwise for i i-, call it LR, RL.
- [x] Test if all flavors still run

### Release notes

Correct import of PE-polar directions for M0.

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

Close #1415

### CODE REVIEW

**Comment by jan-petr** [comment]
Issues with some Flavors...
COMPARISON TABLE:
                       flavor                              dataset                      name                                                  message                                    
    _____________________________________________    ____________________    __________________________    ______________________________________________________________________________

    {'Philips_PCASL_2DEPI_3.2.1.1_dummyQUASAR_1'}    {'rawdata'         }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.json'                                          }
    {'Philips_PCASL_2DEPI_3.2.1.1_dummyQUASAR_1'}    {'rawdata'         }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.nii.gz'                                        }
    {'Philips_PCASL_2DEPI_3.2.1.1_dummyQUASAR_1'}    {'rawdata'         }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_aslcontext.tsv'                                    }
    {'Siemens_PCASL_3DGRASE_VB17A_TopUp_2'      }    {'rawdataReference'}    {'Missing file'          }    {'/sub-SUB002/fmap/sub-SUB002_dir-lr_m0scan.json'                            }
    {'Siemens_PCASL_3DGRASE_VB17A_TopUp_2'      }    {'rawdataReference'}    {'Missing file'          }    {'/sub-SUB002/fmap/sub-SUB002_dir-lr_m0scan.nii.gz'                          }
    {'Siemens_PCASL_3DGRASE_VB17A_TopUp_2'      }    {'rawdataReference'}    {'Missing file'          }    {'/sub-SUB002/perf/sub-SUB002_dir-rl_m0scan.json'                            }
    {'Siemens_PCASL_3DGRASE_VB17A_TopUp_2'      }    {'rawdataReference'}    {'Missing file'          }    {'/sub-SUB002/perf/sub-SUB002_dir-rl_m0scan.nii.gz'                          }
    {'Siemens_PCASL_3DGRASE_VB17A_TopUp_2'      }    {'rawdata'         }    {'Missing file'          }    {'/sub-SUB002/fmap/sub-SUB002_dir-pa_m0scan.json'                            }
    {'Siemens_PCASL_3DGRASE_VB17A_TopUp_2'      }    {'rawdata'         }    {'Missing file'          }    {'/sub-SUB002/fmap/sub-SUB002_dir-pa_m0scan.nii.gz'                          }
    {'Siemens_PCASL_3DGRASE_VB17A_TopUp_2'      }    {'rawdata'         }    {'Missing file'          }    {'/sub-SUB002/perf/sub-SUB002_dir-ap_m0scan.json'                            }
    {'Siemens_PCASL_3DGRASE_VB17A_TopUp_2'      }    {'rawdata'         }    {'Missing file'          }    {'/sub-SUB002/perf/sub-SUB002_dir-ap_m0scan.nii.gz'                          }
    {'Siemens_PCASL_3DGRASE_VB17A_TopUp_2'      }    {'Both'            }    {'Different file content'}    {'Different file content: /sub-SUB002/perf/sub-SUB002_asl.json'              }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'     }    {'rawdataReference'}    {'Missing file'          }    {'/sub-sub1100189/fmap/sub-sub1100189_dir-lr_run-1_m0scan.json'              }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'     }    {'rawdataReference'}    {'Missing file'          }    {'/sub-sub1100189/fmap/sub-sub1100189_dir-lr_run-1_m0scan.nii.gz'            }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'     }    {'rawdataReference'}    {'Missing file'          }    {'/sub-sub1100189/perf/sub-sub1100189_dir-rl_run-1_m0scan.json'              }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'     }    {'rawdataReference'}    {'Missing file'          }    {'/sub-sub1100189/perf/sub-sub1100189_dir-rl_run-1_m0scan.nii.gz'            }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'     }    {'rawdata'         }    {'Missing file'          }    {'/sub-sub1100189/fmap/sub-sub1100189_dir-pa_run-1_m0scan.json'              }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'     }    {'rawdata'         }    {'Missing file'          }    {'/sub-sub1100189/fmap/sub-sub1100189_dir-pa_run-1_m0scan.nii.gz'            }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'     }    {'rawdata'         }    {'Missing file'          }    {'/sub-sub1100189/perf/sub-sub1100189_dir-ap_run-1_m0scan.json'              }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'     }    {'rawdata'         }    {'Missing file'          }    {'/sub-sub1100189/perf/sub-sub1100189_dir-ap_run-1_m0scan.nii.gz'            }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'     }    {'Both'            }    {'Different file content'}    {'Different file content: /sub-sub1100189/perf/sub-sub1100189_run-1_asl.json'}
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD_2'    }    {'rawdataReference'}    {'Missing file'          }    {'/sub-1002/ses-1/fmap/sub-1002_ses-1_dir-ap_m0scan.json'                    }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD_2'    }    {'rawdataReference'}    {'Missing file'          }    {'/sub-1002/ses-1/fmap/sub-1002_ses-1_dir-ap_m0scan.nii.gz'                  }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD_2'    }    {'rawdata'         }    {'Missing file'          }    {'/sub-1002/ses-1/fmap/sub-1002_ses-1_dir-pa_m0scan.json'                    }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD_2'    }    {'rawdata'         }    {'Missing file'          }    {'/sub-1002/ses-1/fmap/sub-1002_ses-1_dir-pa_m0scan.nii.gz'                  }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD_2'    }    {'Both'            }    {'Different file content'}    {'Different file content: /sub-1002/ses-1/perf/sub-1002_ses-1_asl.json'      }
    {'Philips_PCASL_2DEPI_3.2.1.1_dummyQUASAR_1'}    {'derivatives'     }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'                                   }
    {'Philips_PCASL_2DEPI_3.2.1.1_dummyQUASAR_1'}    {'derivatives'     }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.nii.gz'                                 }
    {'Philips_PCASL_2DEPI_3.2.1.1_dummyQUASAR_1'}    {'derivatives'     }    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4Dcontext.tsv'                             }
    {'Siemens_PCASL_3DGRASE_VB17A_TopUp_2'      }    {'Both'            }    {'Different file content'}    {'Different file content: /ExploreASL/sub-SUB002_1/ASL_1/ASL4D.json'         }
    {'Siemens_PCASL_3DGRASE_VB17A_TopUp_2'      }    {'Both'            }    {'Different file content'}    {'Different file content: /ExploreASL/sub-SUB002_1/ASL_1/M0.json'            }
    {'Siemens_PCASL_3DGRASE_VB17A_TopUp_2'      }    {'Both'            }    {'Different file content'}    {'Different file content: /ExploreASL/sub-SUB002_1/ASL_1/M0_RevPE.json'      }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'     }    {'Both'            }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1100189_1/ASL_1/ASL4D.json'     }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'     }    {'Both'            }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1100189_1/ASL_1/M0.json'        }
    {'Siemens_PCASL_3DGRASE_VE11C_DEBBIE_1'     }    {'Both'            }    {'Different file content'}    {'Different file content: /ExploreASL/sub-sub1100189_1/ASL_1/M0_RevPE.json'  }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD_2'    }    {'Both'            }    {'Different file content'}    {'Different file content: /ExploreASL/sub-1002/ASL_1/ASL4D.json'             }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD_2'    }    {'Both'            }    {'Different file content'}    {'Different file content: /ExploreASL/sub-1002/ASL_1/ASL4D_Source.json'      }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD_2'    }    {'Both'            }    {'Different file content'}    {'Different file content: /ExploreASL/sub-1002/ASL_1/M0.json'                }
    {'Siemens_PCASL_3DGRASE_XA31_multiPLD_2'    }    {'Both'            }    {'Different file content'}    {'Different file content: /ExploreASL/sub-1002/ASL_1/M0_RevPE.json'          }

LOGGING TABLE:

**Comment by jan-petr** [comment]
This was mostly fixing the LR vs AP order in flavors to update to the correct version.

**Comment by jan-petr** [comment]
All solved, but `Philips_PCASL_2DEPI_3.2.1.1_dummyQUASAR_1` needs to be imported correctly

**Comment by jan-petr** [comment]
All fixed and the entire flavors work now.

**Review by HenkMutsaerts — APPROVED** [review]
Looks good. I don't know if it should be `dir-si` and `dir-is`, that was an educated guess :) But that seems fine according to BIDS.

We need to change the order for M0 so that it is i j k there as well (for readability).
We could also put this code in a subfunction.

Should we throw a warning if the phase encoding direction is not specified?

**Comment by jan-petr** [comment]
SI-IS was a good guess.

IJK order - will do. But not a sub, because for PERev - we need both normal and inverted to put as a reference field to JSON. So easier without a subfunction.

Yes - warning for missing direction!

**Pull request merged**
