### PR TITLE
Feature #845 x asl system

### LINKED ISSUE #845: xASL_system
### Description

Inspired by issue 88 and `xASL_adm_UnixPath`, I suggest we create a single `xASL_system` function that can always be used to include:

* WSL support
* Deployment support (but with/without compilation should work similarly)
* escaping whitespace & other (semi-)illegal characters (both in Windows & Unix-like)
* other functionality in `xASL_adm_UnixPath`
* Solve for xASL_SysMove the following comment to issue 88: https://github.com/ExploreASL/ExploreASL/issues/88#issuecomment-701207115
* Add Linux initialization such as `source ~./bashrc` that may initialize some things needed for e.g., git to run properly (if another git version is specified in this startup script that is then not found by Matlab when performing system calls, e.g., for git pulling from Matlab).

See also [HERE](https://superuser.com/questions/279008/how-do-i-escape-spaces-in-command-line-in-windows-without-using-quotation-marks)

I've copied this from the original issue #172, and closed it as duplicate, as Michael here took a different stab at this than the original idea :) (sorry @MichaelStritt for the misunderstanding :)
* I've now created `xASL_system` to initialise bash or zsh (depending on Linux or macOS), which should enable e.g., git cloning within a system call from Matlab.
* I've adapted `xASL_qc_TestExploreASL` accordingly

### Requirements

Optional: add feature requirements here

### How to test

Optional: insert description about how to test the code changes here

### Release notes

Required: summarize the changes for the release notes here

### PR DESCRIPTION
**Pull request by HenkMutsaerts**
### Linked issue

Closes #845 (partly)

### How to test

See header of `xASL_system`. We should be able to merge this now, and improve this function later (according to #845), so then the other Wishlist contents from #845 can then be moved to a new issue :)

### Comments

Optional: add helpful comments for the reviewers here

### CODE REVIEW

**Review by MichaelStritt — CHANGES_REQUESTED** [review]
@HenkMutsaerts: code looks good to me and I really don't like to be the guy who says this, but we agreed during the v1.8.0 release to either show examples of tests you did for the changes or to add a code example on how to test it. This will help us to have a less stressful release process next time.

Besides that: great header, looks awesome and makes the docu process a lot easier.

**Comment by HenkMutsaerts** [comment]
Thanks! Good idea, do you something like :

To test this PR:
* run `xASL_system` with the examples shown in its header
* run `xASL_qc_TestExploreASL` in Linux and Windows, with the option for git pulling enabled. Already tested in macOS

**Comment by MichaelStritt** [comment]
> 
> 
> Thanks! Good idea, do you something like :
> 
> To test this PR:
> 
>     * run `xASL_system` with the examples shown in its header
> 
>     * run `xASL_qc_TestExploreASL` in Linux and Windows, with the option for git pulling enabled. Already tested in macOS

Exactly, something like this.

I tested these cases:

```
>> xASL_system('echo hello');
hello 
>> [Result1, Result2] = xASL_system('git fetch');
>> [Result1, Result2] = xASL_system('git pull');
Already up to date.
>> [Result1, Result2] = xASL_system('git status');
On branch feature-#845_xASL_system
Your branch is up to date with 'origin/feature-#845_xASL_system'.

nothing to commit, working tree clean
```

That stuff seems to work fine 👍

**Review by MichaelStritt — APPROVED** [review]
Had to do some minor changes to make it work on windows as well 👍

**Pull request merged**
