### PR TITLE
Closes #394 Revamp import module

### LINKED ISSUE #394: Make Import functions more modular
- Remove the duplicity between ExploreASL_Import and ExploreASL_ImportBIDS
- Put all possible parts of code to separate subfunctions for these two functions
- Improve the modularity and readability of the code.
- Make it modular enough so that Beatriz can run the json parsing only for fixing OASIS.

#### Things we could start with
1. Create a subfolder `SubModule_Import` within the `Modules` folder 👍 
2. Move `ExploreASL_ImportBIDS` to the `Modules folder` 👍 
3. Add the `SubModule_Import` folder to the function `addExploreASLDirectory(MyPath)` in `ExploreASL_Initialize 👍 
4. Move the subfunctions of `ExploreASL_ImportBIDS` as separate scripts to the `SubModule_Import` folder 👍 

#### Compare `ExploreASL_ImportBIDS` and `ExploreASL_Import` versions for...
- `CatchErrors`
- `AppendNiftiParameters`
- `AppendParmsParameters`

#### Use `ExploreASL_ImportBIDS_DCM2NII` within `ExploreASL_Import`

- `ExploreASL_Import` uses `_imp_` subfunctions now 👍 
- **TODO**

#### Fix remaining bugs during flavor processing

- **TODO**

#### Create new subfunctions for...
- create summary file 👍 
- xASL_imp_DCM2NII_Initialize 👍 
- xASL_imp_DCM2NII_Subject 👍 
- xASL_imp_NII2BIDS_Subject 👍 

#### Write cases from `ExploreASL_ImportConfig` to `JSONs`

- Check out `BIDS_createTemplatesImportConfig` 👍 

#### Remove `ExploreASL_ImportConfig` step by step

- Check out the `ConfigFiles` folder within the `CustomScripts` repository 👍 
- Check out the simplified `ExploreASL_ImportConfig` script 👍 

#### OASIS related JSON metadata fix?

- **TODO**

### PR DESCRIPTION
**Pull request by MichaelStritt**
There are possibly quite a lot of bugs left, but I thought I'd start the review process, since I could need some help...

I ran the `BIDS_fullPipelineTest` yesterday and this is the **logContent** file:

[logContent.xlsx](https://github.com/ExploreASL/ExploreASL/files/6383197/logContent.xlsx)

@jan-petr: Did you find time to check if the reference data is correct, regarding the ASL context (deltaM,M0 etc.)?

### CODE REVIEW

**Comment by MichaelStritt** [comment]
@jan-petr: I ran the GE flavors with the up-to-date version of the FlavorDatabase and your recent changes. These are the more troublesome results.

## GE Flavors

### GE_PCASL_2DEPI_volunteer

```
Warning: The following user defined and DICOM fields differ:
  SliceTiming TotalAcquiredPairs
```

Is this problematic?

### GE_PCASL_3Dspiral_Product_volunteer

```
Warning: Had to set non-zero values for m0scan to zero in PostLabelingDelay 
Warning: Had to set non-zero values for m0scan to zero in LabelingDuration 
Warning: Different file content: \sub-Sub1\perf\sub-Sub1_asl.json 
Warning: RMSE of NIFTIs above threshold: \sub-Sub1\perf\sub-Sub1_asl.nii.gz  
```

```
File:	\sub-Sub1\perf\sub-Sub1_asl.json
	Different value: LabelingDuration (check arrays)
	[0.0000, 0.0000]
	[0.0000, 1.4500]
	Different value: PostLabelingDelay (check arrays)
	[0.0000, 0.0000]
	[0.0000, 1.5250]
File:	\sub-Sub1\perf\sub-Sub1_asl.nii.gz
	RMSE     (1.679016e+00)
	MIN-DIFF (0)
	MAX-DIFF (0)
```

```
ERROR: ASL module terminated for subject 1: sub-Sub1
ans =
    'Error using xASL_quant_SinglePLD (line 96)
     Wrong PLD definition!
     Error in xASL_wrp_Quantify (line 279)
     [~, CBF] = xASL_quant_SinglePLD(PWI, M0_im, SliceGradient, x);
```

This was the only error that occurred and it should be a result of the corresponding PLD warning of the import.

### GE_PCASL_3Dspiral_WIP_pharma

```
Warning: Different file content: \sub-1000\perf\sub-1000_m0scan.json 
File:	\sub-1000\perf\sub-1000_m0scan.json
	Different value: IntendedFor 
	(perf\sub-1000_asl.nii.gz vs perf/sub-1000_asl.nii.gz)
```

I think we can safely ignore this one 👍 

### GE_PCASL_3Dspiral_volunteer

```
Warning: RMSE of NIFTIs above threshold: \sub-Sub103\perf\sub-Sub103_asl.nii.gz    
File:	\sub-Sub103\perf\sub-Sub103_asl.nii.gz
	RMSE     (1.693182e+00)
	MIN-DIFF (0)
	MAX-DIFF (0)
```

The min-diff and max-diff are both zero, so I think here the ordering is probably still wrong/different compared to the reference.

**Comment by jan-petr** [comment]
> ## GE Flavors
> ### GE_PCASL_2DEPI_volunteer
> Warning: The following user defined and DICOM fields differ:
>   SliceTiming TotalAcquiredPairs

This is fine. It only means that these two are provided in studyPar.json to override the DICOM values - that's on purpose.

> ### GE_PCASL_3Dspiral_Product_volunteer
> ```
> Warning: Had to set non-zero values for m0scan to zero in PostLabelingDelay 
> Warning: Had to set non-zero values for m0scan to zero in LabelingDuration 

I now check that if PLD is a vector that all m0scans are 0 and if not, sets them to zero. For this sequence, it comes as 
[0.0000, 1.4500] from DICOM and ASLcontext is m0scan,deltaM. So it can stay [0, 1.45]. But on Windows, this is obviously reversed. So it is again the order of dynamics problem... 

> ERROR: ASL module terminated for subject 1: sub-Sub1
>     'Error using xASL_quant_SinglePLD (line 96)
>      Wrong PLD definition!
> This was the only error that occurred and it should be a result of the corresponding PLD warning of the import.

Yes - related to wrong PLD, related to dynamics order
 
> ### GE_PCASL_3Dspiral_WIP_pharma
> Warning: Different file content: \sub-1000\perf\sub-1000_m0scan.json 
> File:	\sub-1000\perf\sub-1000_m0scan.json
> 	Different value: IntendedFor 
> 	(perf\sub-1000_asl.nii.gz vs perf/sub-1000_asl.nii.gz)
> I think we can safely ignore this one 

Yes - to be ignored and to be changed in the comparison script ;)
 
> ### GE_PCASL_3Dspiral_volunteer

Yes - ordering still wrong in some cases - everything else seems to be fine. On Linux, all still works with your latest changes and I didn't have to change the Flavors. Can you try to check these two cases?

**Comment by MichaelStritt** [comment]
@BeatrizPadrela: You said that you encountered a minor bug with the DDI data within the develop branch. Do you want to check if it also appears in this one `revamp-#394_ImportModule`?

**Comment by BeatrizPadrela** [comment]
> @BeatrizPadrela: You said that you encountered a minor bug with the DDI data within the develop branch. Do you want to check if it also appears in this one `revamp-#394_ImportModule`?

The line: `[x]=ExploreASL('/home/bestevespadrela/lood_storage/divi/Projects/ExploreASL/DDI/Philips Medical Systems_Achieva_3.2.1_3.2.1.1/sourceStructure.json',[1 0 0 0], 0, 0, 1, 1)`

is giving the same error
`Undefined function or variable 'scan_name'.`

Maybe the problem is not with the import module but with the data

**Comment by MichaelStritt** [comment]
Nope, I think it's really just not initialized properly. I just checked the `ExploreASL_ImportBIDS_DCM2NII` function within `ExploreASL_ImportBIDS` from `develop`, but there it seems to be exactly the same (not initialized between lines 446-726).

**Comment by MichaelStritt** [comment]
So the problem is here:

```matlab
% convert scan ID to a suitable name and set scan-specific parameters
if size(imPar.tokenScanAliases,2)==2
	iAlias = find(~cellfun(@isempty,regexpi(scanID,imPar.tokenScanAliases(:,1),'once')));
	if ~isempty(iAlias)
		scanNames{iScan} = imPar.tokenScanAliases{iAlias,2};
	else
		% keep the original name
		WarningMessage = ['ExploreASL_Import: Unknown scan ID ' scanID ' found, don"t know what this is'];
		dcm2niiCatchedErrors = CatchErrors('isempty(iAlias)', WarningMessage, dbstack, mfilename, pwd, scan_name, scanpath, destdir, dcm2niiCatchedErrors, imPar);
	end
end
scan_name = scanNames{iScan};
```

The `scanNames` should be initialized correctly. Can we use them instead for the `else`-statement?

Something like this?

```matlab
% convert scan ID to a suitable name and set scan-specific parameters
if size(imPar.tokenScanAliases,2)==2
	iAlias = find(~cellfun(@isempty,regexpi(scanID,imPar.tokenScanAliases(:,1),'once')));
	if ~isempty(iAlias)
		scanNames{iScan} = imPar.tokenScanAliases{iAlias,2};
	else
		% keep the original name
		WarningMessage = ['ExploreASL_Import: Unknown scan ID ' scanID ' found, don"t know what this is'];
		scan_name = scanNames; % ???
		dcm2niiCatchedErrors = CatchErrors('isempty(iAlias)', WarningMessage, dbstack, mfilename, pwd, scan_name, scanpath, destdir, dcm2niiCatchedErrors, imPar);
	end
end
scan_name = scanNames{iScan};
```

This doesn't seem to happen for the flavors, because I tested them...

It should work with correct `imPar.tokenScanAliases`, right?

**Comment by jan-petr** [comment]
> > @BeatrizPadrela: You said that you encountered a minor bug with the DDI data within the develop branch. Do you want to check if it also appears in this one `revamp-#394_ImportModule`?
> 
> This line ...
> `[x] = ExploreASL('/home/bestevespadrela/lood_storage/divi/Projects/ExploreASL/DDI/Philips Medical Systems_Achieva_3.2.1_3.2.1.1/sourceStructure.json',[1 0 0 0], 0, 0, 1, 1)`

@BeatrizPadrela What I note here is the space in the folder name. We were trying to fix those, but this is still a discouraged practice. Can you check again but replacing space with an underscore? And if this help then create an issue so that we can fix that.

**Comment by MichaelStritt** [comment]
> 
> 
> > > @BeatrizPadrela: You said that you encountered a minor bug with the DDI data within the develop branch. Do you want to check if it also appears in this one `revamp-#394_ImportModule`?
> > 
> > 
> > This line ...
> > `[x] = ExploreASL('/home/bestevespadrela/lood_storage/divi/Projects/ExploreASL/DDI/Philips Medical Systems_Achieva_3.2.1_3.2.1.1/sourceStructure.json',[1 0 0 0], 0, 0, 1, 1)`
> 
> @BeatrizPadrela What I note here is the space in the folder name. We were trying to fix those, but this is still a discouraged practice. Can you check again but replacing space with an underscore? And if this help then create an issue so that we can fix that.

Sorry Jan, I think we found the bug. There was a mistake in her `sourceStructure.json`.
It's still a minor bug in the code as well. I'll commit in a few minutes and then you can check if that's okay.

**Comment by MichaelStritt** [comment]
### GE_PCASL_3Dspiral_Product_volunteer

```
ExploreASL v1.5.1 initialized ... 
Dataset: GE_PCASL_3Dspiral_Product_volunteer
File:			\sub-Sub1\perf\sub-Sub1_asl.json
				Different value: LabelingDuration (check arrays)
				[0.0000, 0.0000]
				[0.0000, 1.4500]
				Different value: PostLabelingDelay (check arrays)
				[0.0000, 0.0000]
				[0.0000, 1.5250]
File:			\sub-Sub1\perf\sub-Sub1_asl.nii.gz
				RMSE     (1.679016e+00)
				MIN-DIFF (0)
				MAX-DIFF (0)
```

I just checked the ordering. Your original function and my new function give us `'deltam,m0scan'`. I checked the DICOMs and even there that seems to be correct.

```
ASLContext = 'deltam,m0scan'
realASLContext = 'deltam,m0scan'
```

The reference data has `volume_type: m0scan, deltam` within the `asl_context.json`. So the reference with respect to it's context file is correct, but it's just not right according to the InstanceNumbers, right?

**Comment by MichaelStritt** [comment]
@jan-petr: Please quickly check out if bdfb958 and 137e279 are not totally stupid. They probably don't lead to the desired results, but ExploreASL doesn't crash anymore if the `tokenScanAliases` are wrong.

**Comment by jan-petr** [comment]
Looks good. I will check the GE on my Windows tomorrow...

**Comment by MichaelStritt** [comment]
> Looks good. I will check the GE on my Windows tomorrow...

Thanks 👍

**Comment by MichaelStritt** [comment]
### Idea

- Open a new issue
- In `_DCM2NII_Subject`, directly before the try statement in line 199 split based on `_StoreJSON` and `realASLContext` to subfolders, run dcm2nii on each subfolder
- ...

**Comment by MichaelStritt** [comment]
@jan-petr: can you approve this and then we do the rest in #514 ?

**Review by jan-petr — APPROVED** [review]
OK. BTW: I have always used the testing script, so I have really take note of how the call of import changed. The procedure for calling ExploreASL_Import hasn't really changed and the ImportConfig file is still there? Although the content is moved to JSONs?! I am just thinking that we want to avoid people mailing us immediately about import not working after the merge.

**Comment by MichaelStritt** [comment]
> 
> 
> OK. BTW: I have always used the testing script, so I have really take note of how the call of import changed. The procedure for calling ExploreASL_Import hasn't really changed and the ImportConfig file is still there? Although the content is moved to JSONs?! I am just thinking that we want to avoid people mailing us immediately about import not working after the merge.

So the `ImportConfig` should still work, but it works with the JSONs now. Henk and you said that you want the config files in Development and there they are. I just moved the logic:

image

Already messages you about the `ExploreASL_Import`. I can copy paste the changes from `xASL_Module_Import`, but we don't have a nice method to properly test those changes right now, at least as far as I know. So either with start fading out the support for `ExploreASL_Import` or we should call `xASL_Module_Import` with specific settings, right?

**Comment by MichaelStritt** [comment]
### Test

```
>> imPar = ExploreASL_ImportConfig('M:\SoftwareDevelopment\MATLAB\m.stritt\Server_xASL\testStudy\incoming');
ExploreASL will run the initialization...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath				
Import Modules			   
Process Modules			  
bPause					0
iWorker					1
nWorkers				1
==============================================================================================
ExploreASL v1.5.1 initialized ... 
```

```
>> ExploreASL_Import(imPar);
ExploreASL will run the initialization...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath				
Import Modules			   
Process Modules			  
bPause					0
iWorker					1
nWorkers				1
==============================================================================================
ExploreASL v1.5.1 initialized ... 
Checking permissions: 100%

Matching files:
    'sub-001\visit-001\ASL'

#=1
Running import (i.e. dcm2niiX)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Importing subject=sub_1:   
>>> Subject=sub, visit=1, session=1, scan=ASL4D
executing: ["M:\SoftwareDevelopment\MATLAB\m.stritt\Server_xASL\ExploreASL\External\MRIcron\20190902\dcm2nii.exe"  -o "M:\SoftwareDevelopment\MATLAB\m.stritt\Server_xASL\testStudy\incoming\analysis\sub\ASL_1\dcm2nii_temp_ASL4D" "M:\SoftwareDevelopment\MATLAB\m.stritt\Server_xASL\testStudy\incoming\raw\sub-001\visit-001\ASL\MR.1.2.276.0.7230010.3.1.4.8323329.2149164.1603911083.85348100003.dcm"]
Chris Rorden's dcm2niiX version v1.0.20190902  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1900 (64-bit Windows) 
Found 2800 DICOM file(s) 
Warning: Empty protocol name(s) (0018,1030) 
Warning: Guessing slice times using ProtocolBlock SliceOrder=0 (seq=0, int=1) 
Warning: Unable to append protocol name (0018,1030) to filename (it is empty). 
Convert 2800 DICOM as M:\SoftwareDevelopment\MATLAB\m.stritt\Server_xASL\testStudy\incoming\analysis\sub\ASL_1\dcm2nii_temp_ASL4D\ASL__20140124194612_6 (64x64x20x140) 
Conversion required 16.677999 seconds. 
--------------------------------------------------------------------------------
Chris Rorden's dcm2niiX version v1.0.20190902  (JP2:OpenJPEG) (JP-LS:CharLS) MSC1900 (64-bit Windows)
Found 2800 DICOM file(s)
Warning: Empty protocol name(s) (0018,1030)
Warning: Guessing slice times using ProtocolBlock SliceOrder=0 (seq=0, int=1)
Warning: Unable to append protocol name (0018,1030) to filename (it is empty).
Convert 2800 DICOM as M:\SoftwareDevelopment\MATLAB\m.stritt\Server_xASL\testStudy\incoming\analysis\sub\ASL_1\dcm2nii_temp_ASL4D\ASL__20140124194612_6 (64x64x20x140)
Conversion required 16.677999 seconds.
--------------------------------------------------------------------------------
status: 0
Recreating parameter file: M:\SoftwareDevelopment\MATLAB\m.stritt\Server_xASL\testStudy\incoming\analysis\sub\ASL_1\ASL4D.json
Parameter RescaleSlopeOriginal not found, default used
Parameter MRScaleSlope not found, default used
Parameter RWVIntercept not found, default used
Parameter RWVSlope not found, default used
Parameter AssetRFactor not found, default used
Parameter EffectiveEchoSpacing not found, default used
Parameter GELabelingDuration not found, default used
Parameter InversionTime not found, default us100%Field ImageType contains empty fields, skipping
```

**Comment by MichaelStritt** [comment]
@jan-petr: If you want to can re-check the last 5 commits. All the config files should work now together with the ImportConfig script. I had to find a way to store the `tokenAliases` of the visits, sessions & scans. I store them as a JSON list now and read them pair-wise within ImportConfig. Probably the best way.

**Comment by jan-petr** [comment]
> @jan-petr: If you want to can re-check the last 5 commits. All the config files should work now together with the ImportConfig script. I had to find a way to store the `tokenAliases` of the visits, sessions & scans. I store them as a JSON list now and read them pair-wise within ImportConfig. Probably the best way.

Agree. Time to merge...

**Pull request merged**
