### PR TITLE
Bug #713 structural module error

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

#713

### CODE REVIEW

**Comment by MichaelStritt** [comment]
I think I found my main bug. Within `xASL_init_DataLoading` I'm doing the loading of the dataPar.json, just like we normally did. So there we call `xASL_init_LoadDataParameterFile`. Within `xASL_init_LoadDataParameterFile` we read in `x.D.ROOT`.
In `ExploreASL_Initialize` before `xASL_init_DataLoading`, however, we run `xASL_init_DefinePaths`. This doesn't seem to be data independent at all, since it runs `xASL_init_DefinePaths` which itself requires `x.D.ROOT`.

**Comment by MichaelStritt** [comment]
### Philips_2DEPI_FLAIRsegmentation_PWI4D_QuantificationParameters_LoQ

image

These things can be fixed quite easily 👍

**Comment by MichaelStritt** [comment]
### Bug that Jan discovered already

```matlab
------------------------------------------------------------------------
CAT Preprocessing error for T1:
------------------------------------------------------------------------
Reference to non-existent field 'YlesionFull'.
------------------------------------------------------------------------
  611 - cat_main
  842 - cat_run_job
   21 - cat_run_newcatch
  866 - run_job
  451 - cat_run
   29 - cfg_run_cm
 1692 - local_runcj
  959 - cfg_util
  470 - fill_run_job
  248 - spm_jobman
  609 - xASL_wrp_CAT12Segmentation
  179 - xASL_wrp_SegmentT1w
  378 - xASL_module_Structural
  394 - runIteration
  100 - xASL_Iteration
   43 - ExploreASL_ProcessMaster
   82 - ExploreASL_Master
  340 - xASL_qc_TestExploreASL
------------------------------------------------------------------------

Print 'Graphics' figure to: 
  .\Philips_2DEPI_Lesion_NoFLAIR_NoM0_HiQ\Sub-0001\report\catreport_SPM12.pdf
  Remove ".\Philips_2DEPI_Lesion_NoFLAIR_NoM0_HiQ\Sub-0001\mri\p1T1.nii" 
from dependency list because it does not exist!
One or multiple files do not exist and were removed from the dependency list 
and following batches will may not work correctly!

  Remove ".\Philips_2DEPI_Lesion_NoFLAIR_NoM0_HiQ\Sub-0001\mri\p2T1.nii" 
from dependency list because it does not exist!
One or multiple files do not exist and were removed from the dependency list 
and following batches will may not work correctly!

  Remove ".\Philips_2DEPI_Lesion_NoFLAIR_NoM0_HiQ\Sub-0001\mri\p0T1.nii" 
from dependency list because it does not exist!
One or multiple files do not exist and were removed from the dependency list 
and following batches will may not work correctly!
...
```

**Review by MichaelStritt — APPROVED** [review]

**Review by BeatrizPadrela — APPROVED** [review]
Works on afivasc data!

**Comment by MichaelStritt** [comment]
### Test datasets

image

**Comment by MichaelStritt** [comment]
### BIDS conversion test

image

**Review by HenkMutsaerts — APPROVED** [review]
Looks good!

**Comment by HenkMutsaerts** [comment]
@MichaelStritt continues deserving more beer. Be careful not to work too hard or you'll be very drunk at the ExploreASL workshop in September ;)

**Pull request merged**
