### PR TITLE
Feature #572 restructure nii2 bids

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

#572 

### How to test

Run import of BIDS flavors DCM->BIDS and verify.

### CODE REVIEW

**Review by MichaelStritt — CHANGES_REQUESTED** [review]
@jan-petr: I checked the new scripts. Really great work, seems like you simplified the code a lot!

I tested the conversion using 2 GE, 2 Philips and 2 Siemens flavors.

The comparison step shows no issues at all:
```
>> xASL_test_BIDSFlavorsFull(pathExploreASL, pathTest, [0 0 1 0 0 0 0], x);
ExploreASL will run the initialization...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
Dataset Root        
Import Modules      
Process Modules     
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.7.0_BETA initialized ... 
Dataset: GE_PCASL_3Dspiral_Product_pharma
Dataset: GE_PCASL_3Dspiral_volunteer
Dataset: Philips_PCASL_2DEPI_Bsup_AD1
Dataset: Philips_PCASL_3DGRASE_functional
Dataset: Siemens_PASL_2DEPI_noBsup_AD
Dataset: Siemens_PCASL_3DGRASE_AD
```

The only error that occurred was in the processing of Philips_PCASL_3DGRASE_functional:

```
Couldnt load .\FlavorTests\TmpConversion\Philips_PCASL_3DGRASE_functional
\derivatives\ExploreASL\sub-Patient1\x.mat
3D_GRASE sequence detected
ERROR: ASL module terminated for subject 1: sub-Patient1
ans =
    'Error using <a href="matlab:matlab.internal.language.introspective.errorDocCallback
('xASL_module_ASL', '.\ExploreASL\Modules\xASL_module_ASL.m', 215)" 
style="font-weight:bold">xASL_module_ASL</a> 
(<a href="matlab: opentoline('.\ExploreASL\Modules\xASL_module_ASL.m',215,0)">line 215</a>)
     Invalid ASL image
```

**Comment by jan-petr** [comment]
> I tested the conversion using 2 GE, 2 Philips and 2 Siemens flavors.

Thanks - on Linux, this also works.

> The only error that occurred was in the processing of Philips_PCASL_3DGRASE_functional:
 
Old error - the ASL NIfTIes are not correct, but that's the problem in the source data, not in the import itself. We still have to rework the Flavors that they work start till end, including reasonable values of CBF at the end - that's still a major work to do. But we will have to do issues #603, #604, #605 before that.

**Review by MichaelStritt — APPROVED** [review]
> If that's the only issue, we can wait for Beatriz to test if this helps her to import OASIS and afterwards merge - but we should be sure that no more simplification is needed for OASIS so that we don't need to create a new issue :)

Didn't knew that. Then I'd rather merge now and Beatriz can test it with the other changes of #600, #603 etc. implemented.

**Comment by jan-petr** [comment]
> > If that's the only issue, we can wait for Beatriz to test if this helps her to import OASIS and afterwards merge - but we should be sure that no more simplification is needed for OASIS so that we don't need to create a new issue :)
> 
> Didn't knew that. Then I'd rather merge now and Beatriz can test it with the other changes of #600, #603 etc. implemented.

It's a bit more complex. OASIS is in pseudo-BIDS and we need to get it to full BIDS - mostly we need to process the JSONs. So I have simplified the NII2BIDS that Beatriz can run some subfunctions of that easily. And she needs to test if this is easy enough to use - with this issue. The other issues are unrelated fixes of the BIDS conversion. They also have to be correct so that we provide valid BIDS, but it has nothing to do with this simplification etc. So for that reason, it would be to test the OASIS conversion with a few cases now. Of course #572 can be merged in 1.7.0 if ready and needed, but can wait also for 1.8.0 - it is a non-essential reorganization only.

**Comment by MichaelStritt** [comment]
> 
> 
> > > If that's the only issue, we can wait for Beatriz to test if this helps her to import OASIS and afterwards merge - but we should be sure that no more simplification is needed for OASIS so that we don't need to create a new issue :)
> > 
> > 
> > Didn't knew that. Then I'd rather merge now and Beatriz can test it with the other changes of #600, #603 etc. implemented.
> 
> It's a bit more complex. OASIS is in pseudo-BIDS and we need to get it to full BIDS - mostly we need to process the JSONs. So I have simplified the NII2BIDS that Beatriz can run some subfunctions of that easily. And she needs to test if this is easy enough to use - with this issue. The other issues are unrelated fixes of the BIDS conversion. They also have to be correct so that we provide valid BIDS, but it has nothing to do with this simplification etc. So for that reason, it would be to test the OASIS conversion with a few cases now. Of course #572 can be merged in 1.7.0 if ready and needed, but can wait also for 1.8.0 - it is a non-essential reorganization only.

Ah, makes sense. My main goal right now is to get more data for the machine learning and Henk said that it would be good to use the same ExploreASL version throughout. Let's try to include this in v1.7.0.

**Comment by BeatrizPadrela** [comment]
@jan-petr  so you basically created these functions for the ASL:

First we correct the jsons with  xASL_bids_BIDSifyASLJSON(jsonIn, studyPar, headerASL) and then the NIFTIs with 
 xASL_bids_BIDSifyASLNII(jsonIn, bidsPar, pathIn, pathOutPrefix), using the function bidsPar = xASL_bids_Config() for the input "bidsPar"
 
To correct the Anat jsons, we use xASL_bids_BIDSifyAnatJSON(jsonIn)

And for M0 correction, we can use xASL_bids_BIDSifyM0(jsonIn, jsonInASL, studyPar, pathM0In, pathM0Out, headerASL)

Is that it? For the OASIS script?
The rest of the functions are from the import module right?

**Comment by jan-petr** [comment]
> First we correct the ASL jsons with:
> xASL_imp_NII2BIDS_SubjectSessionRun

Yes, except that you do not call this function, but instead you copy all that is inside to your script. For Anat - these are only 3 functions. For ASL - there's much more, it wasn't possible to contain all in subfunctions. So basically all that is inside, but you have to make sure that you change the filenames correctly in your version of the code. There's plenty of code that takes the old names like `ASL.nii` and create a new name `sub_01_asl.nii` - so you skip all those and fill in your names directly without renaming. You should be able to do all this in your OASIS script in custom-scripts and not modify this branch (unless something unforeseen shows up). Best is to take one dataset from flavors and put brakepoints to see what it does - it should be then rather simple to understand.

> To correct the Anat jsons, we still use:
> jsonAnat = xASL_bids_JsonBIDSifyAnat(jsonAnat); Note this additional function now with different name
> jsonAnat = xASL_bids_VendorFieldCheck(jsonAnat);
> jsonAnat = xASL_bids_JsonCheck(jsonAnat,'');
> right?

Yes exactly. Better check `xASL_imp_NII2BIDS_Subject` for the exact notation, but it should be only these three.
 
> Is that it? For the OASIS script?

Yes - that's it. Copy-paste and adapt these.

> The rest of the functions are from the import module right?

Not sure what you mean here.

Also note - all should be ready for you for preparing the scripts for OASIS and testing. But I need to fix three more issues in import before we run the final conversion of OASIS to BIDS. But these will be internal functions - won't affect your code.

**Comment by BeatrizPadrela** [comment]
> > First we correct the ASL jsons with:
> > xASL_imp_NII2BIDS_SubjectSessionRun
> 
> Yes, except that you do not call this function, but instead you copy all that is inside to your script. For Anat - these are only 3 functions. For ASL - there's much more, it wasn't possible to contain all in subfunctions. So basically all that is inside, but you have to make sure that you change the filenames correctly in your version of the code. There's plenty of code that takes the old names like `ASL.nii` and create a new name `sub_01_asl.nii` - so you skip all those and fill in your names directly without renaming. You should be able to do all this in your OASIS script in custom-scripts and not modify this branch (unless something unforeseen shows up). Best is to take one dataset from flavors and put brakepoints to see what it does - it should be then rather simple to understand.
> 
> > To correct the Anat jsons, we still use:
> > jsonAnat = xASL_bids_JsonBIDSifyAnat(jsonAnat); Note this additional function now with different name
> > jsonAnat = xASL_bids_VendorFieldCheck(jsonAnat);
> > jsonAnat = xASL_bids_JsonCheck(jsonAnat,'');
> > right?
> 
> Yes exactly. Better check `xASL_imp_NII2BIDS_Subject` for the exact notation, but it should be only these three.
> 
> > Is that it? For the OASIS script?
> 
> Yes - that's it. Copy-paste and adapt these.
> 
> > The rest of the functions are from the import module right?
> 
> Not sure what you mean here.
> 
> Also note - all should be ready for you for preparing the scripts for OASIS and testing. But I need to fix three more issues in import before we run the final conversion of OASIS to BIDS. But these will be internal functions - won't affect your code.

Ok I understood everything. And all of these functions are helping improving the import module, nevermind. Thanks! :)

**Review by BeatrizPadrela — APPROVED** [review]
It works!

**Pull request merged**
