### PR TITLE
Bug #353 bids dir ap

### LINKED ISSUE #353: BIDS-Matlab - check for dir-ap in M0scans.
Likewise, `bids-matlab/bids+/layout` probably fails to recognize `Philips_PCASL_3DGRASE_R5.4_TopUp/../perf/sub-Sub1_dir-ap_m0scan`; The issue is that `bids-matlab/bids+/layout`: line 393, assumes no `dir-(ap|pa)`. We can add this if needed, but it should be added then to the original `bids-matlab` repository, which just converted this file to a schema design...

### Release note
Correct conversion BIDS->Legacy for M0 with reversed PE direction

### PR DESCRIPTION
**Pull request by HenkMutsaerts**
closes #353

### CODE REVIEW

**Comment by MichaelStritt** [comment]
Hey Henk, just tried to run all the GE flavors. I know there are still some bugs in there that we're fixing right now within #474 and #514, but this one wasn't there before as far as I know:

```
Error using bids.layout (line 62)
BIDS directory does not exist:
'SoftwareDevelopment\SoftwareDevelopment\MATLAB\m.stritt\Server_xASL\FlavorTests\TmpConversion\GE_PCASL_2DEPI_volunteer\rawdata'
Error in xASL_bids_BIDS2Legacy (line 97)
BIDS = bids.layout(fullfile(pathStudy,'rawdata'));
Error in xASL_test_BIDSFlavorsFull (line 154)
				xASL_bids_BIDS2Legacy(ListFolders{iList}, 1, defaultDataPar);
Error in BIDS_fullPipelineTest (line 73)
xASL_test_BIDSFlavorsFull(pathExploreASL, pathTest, [0 0 0 1 0 0 0], x);
```

**Comment by HenkMutsaerts** [comment]
> Hey Henk, just tried to run all the GE flavors. I know there are still some bugs in there that we're fixing right now within #474 and #514, but this one wasn't there before as far as I know:
> 
> ```
> Error using bids.layout (line 62)
> BIDS directory does not exist:
> .\FlavorTests\TmpConversion\GE_PCASL_2DEPI_volunteer\rawdata'
> Error in xASL_bids_BIDS2Legacy (line 97)
> BIDS = bids.layout(fullfile(pathStudy,'rawdata'));
> Error in xASL_test_BIDSFlavorsFull (line 154)
> 				xASL_bids_BIDS2Legacy(ListFolders{iList}, 1, defaultDataPar);
> Error in BIDS_fullPipelineTest (line 73)
> xASL_test_BIDSFlavorsFull(pathExploreASL, pathTest, [0 0 0 1 0 0 0], x);
> ```

it looks like it's unable to find the folder, did you specify this correctly? Looks like it's a relative path?

**Comment by MichaelStritt** [comment]
> it looks like it's unable to find the folder, did you specify this correctly? Looks like it's a relative path?

Nope, I just removed the part of the path which is only the mediri server address. I use the BIDS_fullPipeline script and that should work at least 95% correctly. How did you test it?

**Comment by HenkMutsaerts** [comment]
> > it looks like it's unable to find the folder, did you specify this correctly? Looks like it's a relative path?
> 
> Nope, I just removed the part of the path which is only the mediri server address. I use the BIDS_fullPipeline script and that should work at least 95% correctly. How did you test it?

I tested it on Mac/ZSH with all flavors using this script: 
https://github.com/ExploreASL/CustomScripts/blob/main/BIDS/ValidationScriptFlavorsBidsInterpretation.m
Can you use this on your server (looks like Windows paths) and see if it works?

One thing I don't understand: you will use all this eventually compiled in a Linux Docker, run by Kubernetes, for mTrial right? Why are you testing using Windows now then (my assumption given the filesep \) ?

**Comment by MichaelStritt** [comment]
> One thing I don't understand: you will use all this eventually compiled in a Linux Docker, run by Kubernetes, for mTrial right? Why are you testing using Windows now then (my assumption given the filesep) ?

So... you don't want ExploreASL to work on windows anymore? :D 

In addition, I hope that we got rid of most of the os path related issues in ExploreASL now. Me testing on windows and you or Jan testing on linux worked pretty good in the past, don't you think? If no one tests on windows until we release, there's some severe bug potential as well.

**Comment by MichaelStritt** [comment]
The bug is in this function `t = canonicalise_path(t, d)` related to the call of `file_utils.m` line 71.

Before `str(n) = canonicalise_path(str(n));` is run we have:

```
str{n}
ans = 'M:\SoftwareDevelopment\MATLAB\m.stritt\Server_xASL\FlavorDatabase\GE_PCASL_2DEPI_volunteer\rawdata'
```

After it was run we have:

```
str{n}
ans ='SoftwareDevelopment\SoftwareDevelopment\MATLAB\m.stritt\Server_xASL\FlavorDatabase\GE_PCASL_2DEPI_volunteer\rawdata'
```

**Comment by HenkMutsaerts** [comment]
> > One thing I don't understand: you will use all this eventually compiled in a Linux Docker, run by Kubernetes, for mTrial right? Why are you testing using Windows now then (my assumption given the filesep) ?
> 
> So... you don't want ExploreASL to work on windows anymore? :D
> 
> In addition, I hope that we got rid of most of the os path related issues in ExploreASL now. Me testing on windows and you or Jan testing on linux worked pretty good in the past, don't you think? If no one tests on windows until we release, there's some severe bug potential as well.

No definitely I agree it is a good thing to keep testing multi-OS. Just takes more time than ensuring Linux only and giving the users the Docker (when we have a user-friendly installer)

**Comment by MichaelStritt** [comment]
Hm... Never worked on those scripts before, but what I don't get are the following things:

In `file_utils.m` line 164, we still have:

```
>> pt{:}
ans =
  8×1 cell array
    {'M:\'                     }
    {'SoftwareDevelopment'     }
    {'MATLAB'                  }
    {'m.stritt'                }
    {'Server_xASL'             }
    {'FlavorDatabase'          }
    {'GE_PCASL_2DEPI_volunteer'}
    {'rawdata'                 }
```

In line 173 we get:

```
> pt{:}
ans =
  1×7 cell array
    {'SoftwareDevelop…'}    {'MATLAB'}    {'m.stritt'}    {'Server_xASL'}    {'FlavorDatabase'}    {'GE_PCASL_2DEPI_…'}    {'rawdata'}
```

And in line 177 we then get:

```
pt{:}
ans =
  1×8 cell array
    {'SoftwareDevelop…'}    {'SoftwareDevelop…'}    {'MATLAB'}    {'m.stritt'}    {'Server_xASL'}    {'FlavorDatabase'}    {'GE_PCASL_2DEPI_…'}    {'rawdata'}
```

So here something's seriously wrong.

**Comment by HenkMutsaerts** [comment]
> The bug is in this function `t = canonicalise_path(t, d)` related to the call of `file_utils.m` line 71.
> 
> Before `str(n) = canonicalise_path(str(n));` is run we have:
> 
> ```
> str{n}
> ans = 'M:\SoftwareDevelopment\MATLAB\m.stritt\Server_xASL\FlavorDatabase\GE_PCASL_2DEPI_volunteer\rawdata'
> ```
> 
> After it was run we have:
> 
> ```
> str{n}
> ans ='SoftwareDevelopment\SoftwareDevelopment\MATLAB\m.stritt\Server_xASL\FlavorDatabase\GE_PCASL_2DEPI_volunteer\rawdata'
> ```

**Comment by HenkMutsaerts** [comment]
> Hm... Never worked on those scripts before, but what I don't get are the following things:
> 
> In `file_utils.m` line 164, we still have:
> 
> ```
> >> pt{:}
> ans =
>   8×1 cell array
>     {'M:\'                     }
>     {'SoftwareDevelopment'     }
>     {'MATLAB'                  }
>     {'m.stritt'                }
>     {'Server_xASL'             }
>     {'FlavorDatabase'          }
>     {'GE_PCASL_2DEPI_volunteer'}
>     {'rawdata'                 }
> ```
> 
> In line 173 we get:
> 
> ```
> > pt{:}
> ans =
>   1×7 cell array
>     {'SoftwareDevelop…'}    {'MATLAB'}    {'m.stritt'}    {'Server_xASL'}    {'FlavorDatabase'}    {'GE_PCASL_2DEPI_…'}    {'rawdata'}
> ```
> 
> And in line 177 we then get:
> 
> ```
> pt{:}
> ans =
>   1×8 cell array
>     {'SoftwareDevelop…'}    {'SoftwareDevelop…'}    {'MATLAB'}    {'m.stritt'}    {'Server_xASL'}    {'FlavorDatabase'}    {'GE_PCASL_2DEPI_…'}    {'rawdata'}
> ```
> 
> So here something's seriously wrong.

These scripts are from `github.com/bids/bids-matlab`, not from ourselves. Perhaps they have fixed this already in new version of this script, I have to update it still but they refactored `/bids+/layout.m` to schema. So you can check if copying their newer `file_utils.m` works, or we can try to fix it if easy, or otherwise, we simply use our own tooling for this:)

Sorry, accidentally closed this issue :)

**Comment by MichaelStritt** [comment]
The [develop](https://github.com/ExploreASL/bids-matlab/blob/dev/%2Bbids/%2Binternal/file_utils.m) version from bids-matlab doesn't seem to be different in that section of the code.

For me, the easiest fix was to remove (8662547) the ispc statements. I'm using an absolute path though, so maybe they were meant to help with relative paths? That would require more extensive testing. My result now after 8662547:

```matlab
Rdir = 'M:\SoftwareDevelopment\MATLAB\m.stritt\Server_xASL\FlavorDatabase';
folderList = xASL_adm_GetFileList(Rdir, '.*', 'FPList', [0 Inf], 1);
for iFolder=1:numel(folderList)
    rawdataFolder = fullfile(folderList{iFolder}, 'rawdata');
    if exist(rawdataFolder, 'dir')
        BIDS = bids.layout(rawdataFolder);
    end
end
```

```console
>> ValidationScriptFlavorsBidsInterpretation.m
Warning: Caution when using control as M0, background suppression was applied 
> In bids.layout>parse_perf (line 409)
  In bids.layout>parse_subject (line 198)
  In bids.layout (line 151)
  In Untitled (line 7) 
Warning: Caution when using control as M0, background suppression was applied 
> In bids.layout>parse_perf (line 409)
  In bids.layout>parse_subject (line 198)
  In bids.layout (line 151)
  In Untitled (line 7) 
Warning: Caution when using control as M0, background suppression was applied 
> In bids.layout>parse_perf (line 409)
  In bids.layout>parse_subject (line 198)
  In bids.layout (line 151)
  In Untitled (line 7) 
Warning: Caution when using control as M0, background suppression was applied 
> In bids.layout>parse_perf (line 409)
  In bids.layout>parse_subject (line 198)
  In bids.layout (line 151)
  In Untitled (line 7) 
Warning: Caution when using control as M0, background suppression was applied 
> In bids.layout>parse_perf (line 409)
  In bids.layout>parse_subject (line 198)
  In bids.layout (line 151)
  In Untitled (line 7) 
```

**Comment by MichaelStritt** [comment]
Do we need to mention this to the `bids-matlab` group?
I can quickly run a few flavors and if you are okay with these changes, we should probably at least write them down in our own changes documentation.

**Comment by MichaelStritt** [comment]
Tested the first three GE datasets. The import seems to work fine. Haven't processed them, since I need Matlab to work on some other things right now ;)

**Review by MichaelStritt — APPROVED** [review]
Would probably be good, if @jan-petr could check this out, too 👍

**Comment by HenkMutsaerts** [comment]
> Would probably be good, if @jan-petr could check this out, too 👍 

Looks good but has it been tested with Unix eg in your docker? It indeed seems that a more thorough fix is needed for the relative path support

**Review by jan-petr — CHANGES_REQUESTED** [review]
Not working for `Philips_PCASL_3DGRASE_R5.4_TopUp` and neither for `Siemens_PCASL_volunteer`.

It only produces the `M0RevPE.nii` and not the normal `M0.nii`.

**Comment by HenkMutsaerts** [comment]
> > Not working for `Philips_PCASL_3DGRASE_R5.4_TopUp` and neither for `Siemens_PCASL_volunteer`.
> > It only produces the `M0RevPE.nii` and not the normal `M0.nii`.
> 
bids-matlab correctly recognizes the fmap/m0scan and perf/m0scan.
When I run:
`pathStudy='/Users/henk/ExploreASL/FlavorDatabase/Siemens_PCASL_volunteer/rawdata';`
`bOverwrite=0;`
`dataPar=[];`
`[dataPar] = xASL_bids_BIDS2Legacy(pathStudy, bOverwrite, dataPar);`
within this branch, it correctly outputs both `M0.nii` and `.M0_RevPE.nii`

**Review by jan-petr — APPROVED** [review]
OK

**Pull request merged**
