### PR TITLE
Closes #518 Introduce bReinitialize

### LINKED ISSUE #518: Avoid verbosity re-initialization
`ExploreASL_Initialize`: `xASL_init_PrintCheckSettings` (line 631) is too verbose when loading a dataset but skipping the import and processing.

Solution: give it a `x.bVerbose` option.
If not specified, `ExploreASL_Initialize` should set `x.bVerbose` to false which will skip `xASL_init_PrintCheckSettings`. 
And then within `ExploreASL_Master` or `ExploreASL_Initialize` (probably the latter):
`if sum(x.bImportData)>0 || sum(x.bProcessData)>0`
`.   x.bVerbose = true;`
`end`

In other words, always skip `xASL_init_PrintCheckSettings` unless `if sum(x.bImportData)>0 || sum(x.bProcessData)>0`

### PR DESCRIPTION
**Pull request by MichaelStritt**
Introduce a bReinitialize to the x struct to handle the reinitialization behavior

### CODE REVIEW

**Comment by MichaelStritt** [comment]
### Test 1: Only initialize

```
>> [x] = ExploreASL_Initialize;
ExploreASL will run the initialization...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath         
Import Modules         
Process Modules       
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.5.1 initialized ... 
>> 
```

👍

**Comment by MichaelStritt** [comment]
### Test 2: Only initialize from ExploreASL_Master

```
>> [x] = ExploreASL_Master;
ExploreASL will run the initialization...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath         
Import Modules         
Process Modules       
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.5.1 initialized ... 
>> 
```

👍

**Comment by MichaelStritt** [comment]
### Test 3: Only load data

```
>> path = fullfile(root,'ExploreASL\External\TestDataSet\analysis\DataParameters_LowQ.json');
>> [x] = ExploreASL_Master(path, 0, 0);
ExploreASL will load the dataset...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath         ..._xASL\ExploreASL\External\TestDataSet\analysis\DataParameters_LowQ.json
Import Modules         
Process Modules       
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.5.1 initialized ... 
Automatically defining sessions...
==================================== Additional Settings =====================================
1 scans - 0 exclusions, resulting in 1 scans of: 
Longitudinal timePoint 1 = 1 scans - 0 exclusions = 1 scans
ASL sessions: 1

Ancillary data, sets: 3 sets are defined for 1 "SubjectsSessions"
Set 1 = "LongitudinalTimePoint" options "TimePoint_1", codes for paired data
Set 2 = "SubjectNList" options "SubjectNList", codes for paired data
Set 3 = "Site" options "SingleSite", codes for two-sample data
x.D.ROOT            ...nt\MATLAB\m.stritt\Server_xASL\ExploreASL\External\TestDataSet\analysis
x.DELETETEMP        1 (delete temporary files)
x.Quality           0 (0 = fast try-out; 1 = normal high quality)

==============================================================================================


>> 
```

```
x = 
  struct with fields:
                         name: 'ExampleDataSet'
               subject_regexp: '^Sub-\d{3}(|_\d*)$'
                      Quality: 0
                  DataParPath: '.\External\TestDataSet\analysis\DataParameters_LowQ.json'
                ImportModules: [0 0 0 0]
               ProcessModules: [0 0 0]
                       bPause: 0
                      iWorker: 1
                     nWorkers: 1
                            S: [1×1 struct]
                bReinitialize: 0
                  bImportData: 0
                 bProcessData: 2
                       MyPath: 'M:\SoftwareDevelopment\MATLAB\m.stritt\Server_xASL\ExploreASL'
                  dataParType: 'dataParFile'
                            D: [1×1 struct]
              stopaftererrors: Inf
                       dryrun: 0
                   bOverwrite: 1
                      Version: '1.5.1'
                            Q: [1×1 struct]
                 SpaghettiDir: '.\External\TestDataSet\analysis\Population\SpaghettiPlots'
                 HistogramDir: '.\External\TestDataSet\analysis\Population\Histograms'
                    StatsMaps: '.\External\TestDataSet\analysis\Population\StatsMaps'
                       SPMDIR: '.\External\SPMmodified'
                      SPMpath: '.\External\SPMmodified'
                   SPMVERSION: 'SPM12'
                        skull: [121×145×121 logical]
                 BILAT_FILTER: 0
                       WBmask: [121×145×121 logical]
                bReproTesting: 0
           Pediatric_Template: 0
               bLesionFilling: 1
                    bAutoACPC: 1
                 SegmentSPM12: 0
    M0_conventionalProcessing: 0
        bGetControlLabelOrder: 1
                TotalSubjects: {'Sub-001'}
               nTotalSubjects: 1
                    exclusion: {''}
                     SESSIONS: {'ASL_1'}
                    nSessions: 1
       TimePointTotalSubjects: {{1×1 cell}}
             ExcludedSubjects: ''
                     SUBJECTS: {'Sub-001'}
           TotalInclusionList: 1
                    nSubjects: 1
                    nExcluded: 0
            nSubjectsSessions: 1
             nTimePointsTotal: 1
      nTimePointTotalSubjects: 1
            TimePointSubjects: {{1×1 cell}}
                  nTimePoints: 1
           nTimePointSubjects: 1
            TimePointExcluded: {''}
           nTimePointExcluded: 0
                   DELETETEMP: 1
                            P: [1×1 struct]
                    StudyRoot: '.\ExploreASL\External\TestDataSet\analysis'
```

👍

**Comment by MichaelStritt** [comment]
### Test 4: Run import workflow & reinitialize

```
>> path = fullfile(root,'Testing\UnitTesting\working_directory\GE\sourceStructure.json');
>> [x] = ExploreASL_Master(path, 1, 0);
ExploreASL will run the import workflow and will run the initialization...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath         ...rver_xASL\Testing\UnitTesting\working_directory\GE\sourceStructure.json
Import Modules      DCM2NII NII2BIDS ANONYMIZE BIDS2LEGACY
Process Modules       
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.5.1 initialized ... 

Matching files:
    'Sub1\ASL'

#=1
Running import (i.e. dcm2niiX)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
...
Creating default dataPar.json since file was not found...
Overwriting x.DataParPath...
ExploreASL will load the dataset...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath         ...ng\UnitTesting\working_directory\GE\derivatives\ExploreASL\DataPar.json
Import Modules         
Process Modules       
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.5.1 initialized ... 
Automatically defining sessions...
==================================== Additional Settings =====================================
1 scans - 0 exclusions, resulting in 1 scans of: 
Longitudinal timePoint 1 = 1 scans - 0 exclusions = 1 scans
ASL sessions: 1

Ancillary data, sets: 3 sets are defined for 1 "SubjectsSessions"
Set 1 = "LongitudinalTimePoint" options "TimePoint_1", codes for paired data
Set 2 = "SubjectNList" options "SubjectNList", codes for paired data
Set 3 = "Site" options "SingleSite", codes for two-sample data
x.D.ROOT            ...er_xASL\Testing\UnitTesting\working_directory\GE\derivatives\ExploreASL
x.DELETETEMP        1 (delete temporary files)
x.Quality           1 (0 = fast try-out; 1 = normal high quality)

==============================================================================================
```

👍

**Comment by MichaelStritt** [comment]
### Test 5: Only run data loading and processing

```
>> path = '.\Testing\UnitTesting\working_directory\TestDataSet\analysis\DataParameters_LowQ.json';
>> [x] = ExploreASL_Master(path, 0, 1);
ExploreASL will run the processing pipeline...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath         ...Testing\working_directory\TestDataSet\analysis\DataParameters_LowQ.json
Import Modules         
Process Modules     Structural ASL Population
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.5.1 initialized ... 
Automatically defining sessions...
==================================== Additional Settings =====================================
1 scans - 0 exclusions, resulting in 1 scans of: 
Longitudinal timePoint 1 = 1 scans - 0 exclusions = 1 scans
ASL sessions: 1

Ancillary data, sets: 3 sets are defined for 1 "SubjectsSessions"
Set 1 = "LongitudinalTimePoint" options "TimePoint_1", codes for paired data
Set 2 = "SubjectNList" options "SubjectNList", codes for paired data
Set 3 = "Site" options "SingleSite", codes for two-sample data
x.D.ROOT            ...\Server_xASL\Testing\UnitTesting\working_directory\TestDataSet\analysis
x.DELETETEMP        1 (delete temporary files)
x.Quality           0 (0 = fast try-out; 1 = normal high quality)

==============================================================================================


ExploreASL will run the processing pipeline...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath         ...Testing\working_directory\TestDataSet\analysis\DataParameters_LowQ.json
Import Modules         
Process Modules     Structural ASL Population
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.5.1 initialized ... 
Automatically defining sessions...
==================================== Additional Settings =====================================
1 scans - 0 exclusions, resulting in 1 scans of: 
Longitudinal timePoint 1 = 1 scans - 0 exclusions = 1 scans
ASL sessions: 1

Ancillary data, sets: 3 sets are defined for 1 "SubjectsSessions"
Set 1 = "LongitudinalTimePoint" options "TimePoint_1", codes for paired data
Set 2 = "SubjectNList" options "SubjectNList", codes for paired data
Set 3 = "Site" options "SingleSite", codes for two-sample data
x.D.ROOT            ...\Server_xASL\Testing\UnitTesting\working_directory\TestDataSet\analysis
x.DELETETEMP        1 (delete temporary files)
x.Quality           0 (0 = fast try-out; 1 = normal high quality)

==============================================================================================


Running xASL_module_Structural ...   
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting xASL_module_Structural at 29-Apr-2021 19:39:12
```

**Comment by MichaelStritt** [comment]
## New version

### Test 1 (redo)

```
>> [x] = ExploreASL_Initialize;
ExploreASL will run the initialization...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath         
Import Modules         
Process Modules       
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.5.1 initialized ... 
```

### Test 2 (redo)

```
>> [x] = ExploreASL_Master;
ExploreASL will run the initialization...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath         
Import Modules         
Process Modules       
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.5.1 initialized ... 
```

### Test 3 (redo)

```
>> path = fullfile(root,'ExploreASL\External\TestDataSet\analysis\DataParameters_LowQ.json');
>> [x] = ExploreASL_Master(path, 0, 0);
ExploreASL will load the dataset...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath         ..._xASL\ExploreASL\External\TestDataSet\analysis\DataParameters_LowQ.json
Import Modules         
Process Modules       
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.5.1 initialized ... 
Automatically defining sessions...
==================================== Additional Settings =====================================
1 scans - 0 exclusions, resulting in 1 scans of: 
Longitudinal timePoint 1 = 1 scans - 0 exclusions = 1 scans
ASL sessions: 1

Ancillary data, sets: 3 sets are defined for 1 "SubjectsSessions"
Set 1 = "LongitudinalTimePoint" options "TimePoint_1", codes for paired data
Set 2 = "SubjectNList" options "SubjectNList", codes for paired data
Set 3 = "Site" options "SingleSite", codes for two-sample data
x.D.ROOT            ...nt\MATLAB\m.stritt\Server_xASL\ExploreASL\External\TestDataSet\analysis
x.DELETETEMP        1 (delete temporary files)
x.Quality           0 (0 = fast try-out; 1 = normal high quality)

==============================================================================================
```

### Test 4 (redo)

```
>> [x] = ExploreASL_Master(path, 1, 0);
ExploreASL will run the import workflow and will run the initialization...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath         ...\Server_xASL\Testing\UnitTesting\working_directory\sourceStructure.json
Import Modules      DCM2NII NII2BIDS ANONYMIZE BIDS2LEGACY
Process Modules       
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.5.1 initialized ... 

Matching files:
    'Sub1\ASL'

#=1
Running import (i.e. dcm2niiX)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Importing subject=Sub1_1:   
>>> Subject=Sub1, visit=1, session=1, scan=ASL4D
...
Creating default dataPar.json since file was not found...
Overwriting x.DataParPath...
ExploreASL will load the dataset...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath         ...sting\UnitTesting\working_directory\derivatives\ExploreASL\DataPar.json
Import Modules         
Process Modules       
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.5.1 initialized ... 
Automatically defining sessions...
==================================== Additional Settings =====================================
1 scans - 0 exclusions, resulting in 1 scans of: 
Longitudinal timePoint 1 = 1 scans - 0 exclusions = 1 scans
ASL sessions: 1

Ancillary data, sets: 3 sets are defined for 1 "SubjectsSessions"
Set 1 = "LongitudinalTimePoint" options "TimePoint_1", codes for paired data
Set 2 = "SubjectNList" options "SubjectNList", codes for paired data
Set 3 = "Site" options "SingleSite", codes for two-sample data
x.D.ROOT            ...erver_xASL\Testing\UnitTesting\working_directory\derivatives\ExploreASL
x.DELETETEMP        1 (delete temporary files)
x.Quality           1 (0 = fast try-out; 1 = normal high quality)

==============================================================================================
```

### Test 5 (redo)

```
>> [x] = ExploreASL_Master(path, 0, 1);
ExploreASL will run the processing pipeline...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath         ...Testing\working_directory\TestDataSet\analysis\DataParameters_LowQ.json
Import Modules         
Process Modules     Structural ASL Population
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.5.1 initialized ... 
Automatically defining sessions...
==================================== Additional Settings =====================================
1 scans - 0 exclusions, resulting in 1 scans of: 
Longitudinal timePoint 1 = 1 scans - 0 exclusions = 1 scans
ASL sessions: 1

Ancillary data, sets: 3 sets are defined for 1 "SubjectsSessions"
Set 1 = "LongitudinalTimePoint" options "TimePoint_1", codes for paired data
Set 2 = "SubjectNList" options "SubjectNList", codes for paired data
Set 3 = "Site" options "SingleSite", codes for two-sample data
x.D.ROOT            ...\Server_xASL\Testing\UnitTesting\working_directory\TestDataSet\analysis
x.DELETETEMP        1 (delete temporary files)
x.Quality           0 (0 = fast try-out; 1 = normal high quality)

==============================================================================================


Running xASL_module_Structural ...   
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Starting xASL_module_Structural at 29-Apr-2021 19:46:59
```

👍

**Comment by MichaelStritt** [comment]
### Test 6 (import and processing)

```
>> path = '.\working_directory\sourceStructure.json';
>> [x] = ExploreASL_Master(path, 1, 1);
ExploreASL will run the import workflow and will run the processing pipeline...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath         ...\Server_xASL\Testing\UnitTesting\working_directory\sourceStructure.json
Import Modules      DCM2NII NII2BIDS ANONYMIZE BIDS2LEGACY
Process Modules     Structural ASL Population
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.5.1 initialized ... 

Matching files:
    'Sub1\ASL'

#=1
Running import (i.e. dcm2niiX)
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Importing subject=Sub1_1:   
>>> Subject=Sub1, visit=1, session=1, scan=ASL4D
...
Creating default dataPar.json since file was not found...
Overwriting x.DataParPath...
ExploreASL will run the processing pipeline...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath         ...sting\UnitTesting\working_directory\derivatives\ExploreASL\DataPar.json
Import Modules         
Process Modules     Structural ASL Population
bPause              False
iWorker             1
nWorkers            1
==============================================================================================
ExploreASL v1.5.1 initialized ... 
Automatically defining sessions...
==================================== Additional Settings =====================================
1 scans - 0 exclusions, resulting in 1 scans of: 
Longitudinal timePoint 1 = 1 scans - 0 exclusions = 1 scans
ASL sessions: 1

Ancillary data, sets: 3 sets are defined for 1 "SubjectsSessions"
Set 1 = "LongitudinalTimePoint" options "TimePoint_1", codes for paired data
Set 2 = "SubjectNList" options "SubjectNList", codes for paired data
Set 3 = "Site" options "SingleSite", codes for two-sample data
x.D.ROOT            ...erver_xASL\Testing\UnitTesting\working_directory\derivatives\ExploreASL
x.DELETETEMP        1 (delete temporary files)
x.Quality           1 (0 = fast try-out; 1 = normal high quality)

==============================================================================================
...
```

**Review by HenkMutsaerts — APPROVED** [review]
Very nice!
Perhaps good for Beatriz to merge? ;)

**Comment by MichaelStritt** [comment]
> 
> 
> Very nice!
> Perhaps good for Beatriz to merge? ;)

Good idea, I reassigned it 👍

**Pull request merged**
