### PR TITLE
Bug #1670 multi t eimport

### LINKED ISSUE #1670: Import bug - Echo times
### Description

From nifti 2 BIDS, there's this bug that 

image

And this is what the rawdata/ASL.json looks like:

image

### Tasks

- [x] Fix multi-TE Phoenix reading
- [x] Fix Flavors
- [x] Add pig flavor with adjusted JSONs

### Release notes

Nothing. Report with #1543

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

Close #1670

### CODE REVIEW

**Comment by BeatrizPadrela** [comment]
Everything looks good in rawdata!!

For run-1 (HAD8) ASL json:
image


and for run-2 (HAD4) ASL json:

image

**Review by BeatrizPadrela — APPROVED** [review]
it works!

**Review by HenkMutsaerts — APPROVED** [review]
As long as we think carefully what goes into dcm2BIDS (correct data structure) and BIDS2legacy (processing options), I'm fine.

This looks great

**Comment by jan-petr** [comment]
___________________________________________

    {'Siemens_PASL_2DEPI_VB17A_BSupN_1'                   }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.json'                            }
    {'Siemens_PASL_2DEPI_VB17A_BSupN_1'                   }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.nii.gz'                          }
    {'Siemens_PASL_2DEPI_VB17A_BSupN_1'                   }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_aslcontext.tsv'                      }
    {'Siemens_PASL_2DEPI_VB17A_BSupN_1'                   }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_m0scan.json'                         }
    {'Siemens_PASL_2DEPI_VB17A_BSupN_1'                   }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_m0scan.nii.gz'                       }
    {'Siemens_PASL_2DEPI_VB17A_BSupN_2'                   }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.json'                            }
    {'Siemens_PASL_2DEPI_VB17A_BSupN_2'                   }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.nii.gz'                          }
    {'Siemens_PASL_2DEPI_VB17A_BSupN_2'                   }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_aslcontext.tsv'                      }
    {'Siemens_PASL_2DEPI_VB17A_ADNI2_941_S_5193_1'        }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.json'                            }
    {'Siemens_PASL_2DEPI_VB17A_ADNI2_941_S_5193_1'        }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.nii.gz'                          }
    {'Siemens_PASL_2DEPI_VB17A_ADNI2_941_S_5193_1'        }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_aslcontext.tsv'                      }
    {'Siemens_PASL_2DEPI_VB19A_BSupN_1'                   }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.json'                            }
    {'Siemens_PASL_2DEPI_VB19A_BSupN_1'                   }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.nii.gz'                          }
    {'Siemens_PASL_2DEPI_VB19A_BSupN_1'                   }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_aslcontext.tsv'                      }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'rawdata'    }    {'Missing file'          }    {'/sub-101/fmap/sub-101_dir-pa_run-1_m0scan.json'              }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'rawdata'    }    {'Missing file'          }    {'/sub-101/fmap/sub-101_dir-pa_run-1_m0scan.nii.gz'            }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'rawdata'    }    {'Missing file'          }    {'/sub-101/fmap/sub-101_dir-pa_run-2_m0scan.json'              }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'rawdata'    }    {'Missing file'          }    {'/sub-101/fmap/sub-101_dir-pa_run-2_m0scan.nii.gz'            }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'rawdata'    }    {'Missing file'          }    {'/sub-101/perf/sub-101_dir-ap_run-1_m0scan.json'              }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'rawdata'    }    {'Missing file'          }    {'/sub-101/perf/sub-101_dir-ap_run-1_m0scan.nii.gz'            }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'rawdata'    }    {'Missing file'          }    {'/sub-101/perf/sub-101_dir-ap_run-2_m0scan.json'              }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'rawdata'    }    {'Missing file'          }    {'/sub-101/perf/sub-101_dir-ap_run-2_m0scan.nii.gz'            }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'rawdata'    }    {'Missing file'          }    {'/sub-101/perf/sub-101_run-1_asl.json'                        }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'rawdata'    }    {'Missing file'          }    {'/sub-101/perf/sub-101_run-1_asl.nii.gz'                      }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'rawdata'    }    {'Missing file'          }    {'/sub-101/perf/sub-101_run-1_aslcontext.tsv'                  }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'rawdata'    }    {'Missing file'          }    {'/sub-101/perf/sub-101_run-2_asl.json'                        }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'rawdata'    }    {'Missing file'          }    {'/sub-101/perf/sub-101_run-2_asl.nii.gz'                      }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'rawdata'    }    {'Missing file'          }    {'/sub-101/perf/sub-101_run-2_aslcontext.tsv'                  }
    {'Siemens_PASL_3DGRASE_VD13D_1'                       }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.json'                            }
    {'Siemens_PASL_3DGRASE_VD13D_1'                       }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.nii.gz'                          }
    {'Siemens_PASL_3DGRASE_VD13D_1'                       }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_aslcontext.tsv'                      }
    {'Siemens_PASL_3DGRASE_VE11C_1'                       }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.json'                            }
    {'Siemens_PASL_3DGRASE_VE11C_1'                       }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.nii.gz'                          }
    {'Siemens_PASL_3DGRASE_VE11C_1'                       }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_aslcontext.tsv'                      }
    {'Siemens_PASL_3DGRASE_VE11C_2'                       }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.json'                            }
    {'Siemens_PASL_3DGRASE_VE11C_2'                       }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_asl.nii.gz'                          }
    {'Siemens_PASL_3DGRASE_VE11C_2'                       }    {'rawdata'    }    {'Missing file'          }    {'/sub-Sub1/perf/sub-Sub1_aslcontext.tsv'                      }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'rawdata'    }    {'Missing file'          }    {'/sub-012S4093/ses-1/perf/sub-012S4093_ses-1_asl.json'        }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'rawdata'    }    {'Missing file'          }    {'/sub-012S4093/ses-1/perf/sub-012S4093_ses-1_asl.nii.gz'      }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'rawdata'    }    {'Missing file'          }    {'/sub-012S4093/ses-1/perf/sub-012S4093_ses-1_aslcontext.tsv'  }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'rawdata'    }    {'Missing file'          }    {'/sub-012S4093/ses-2/perf/sub-012S4093_ses-2_asl.json'        }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'rawdata'    }    {'Missing file'          }    {'/sub-012S4093/ses-2/perf/sub-012S4093_ses-2_asl.nii.gz'      }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'rawdata'    }    {'Missing file'          }    {'/sub-012S4093/ses-2/perf/sub-012S4093_ses-2_aslcontext.tsv'  }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'rawdata'    }    {'Missing file'          }    {'/sub-012S4094/ses-1/perf/sub-012S4094_ses-1_asl.json'        }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'rawdata'    }    {'Missing file'          }    {'/sub-012S4094/ses-1/perf/sub-012S4094_ses-1_asl.nii.gz'      }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'rawdata'    }    {'Missing file'          }    {'/sub-012S4094/ses-1/perf/sub-012S4094_ses-1_aslcontext.tsv'  }
    {'Siemens_PCASL_multiSequence_VE11C_2'                }    {'rawdata'    }    {'Missing file'          }    {'/sub-sub1/perf/sub-sub1_run-1_asl.json'                      }
    {'Siemens_PCASL_multiSequence_VE11C_2'                }    {'rawdata'    }    {'Missing file'          }    {'/sub-sub1/perf/sub-sub1_run-1_asl.nii.gz'                    }
    {'Siemens_PCASL_multiSequence_VE11C_2'                }    {'rawdata'    }    {'Missing file'          }    {'/sub-sub1/perf/sub-sub1_run-1_aslcontext.tsv'                }
    {'Siemens_PCASL_multiSequence_VE11C_2'                }    {'rawdata'    }    {'Missing file'          }    {'/sub-sub1/perf/sub-sub1_run-2_asl.json'                      }
    {'Siemens_PCASL_multiSequence_VE11C_2'                }    {'rawdata'    }    {'Missing file'          }    {'/sub-sub1/perf/sub-sub1_run-2_asl.nii.gz'                    }
    {'Siemens_PCASL_multiSequence_VE11C_2'                }    {'rawdata'    }    {'Missing file'          }    {'/sub-sub1/perf/sub-sub1_run-2_aslcontext.tsv'                }
    {'Siemens_PCASL_multiSequence_VE11C_2'                }    {'rawdata'    }    {'Missing file'          }    {'/sub-sub1/perf/sub-sub1_run-2_m0scan.json'                   }
    {'Siemens_PCASL_multiSequence_VE11C_2'                }    {'rawdata'    }    {'Missing file'          }    {'/sub-sub1/perf/sub-sub1_run-2_m0scan.nii.gz'                 }
    {'Siemens_PASL_2DEPI_VB17A_BSupN_1'                   }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'                     }
    {'Siemens_PASL_2DEPI_VB17A_BSupN_1'                   }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.nii.gz'                   }
    {'Siemens_PASL_2DEPI_VB17A_BSupN_1'                   }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4Dcontext.tsv'               }
    {'Siemens_PASL_2DEPI_VB17A_BSupN_1'                   }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/M0.json'                        }
    {'Siemens_PASL_2DEPI_VB17A_BSupN_1'                   }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/M0.nii.gz'                      }
    {'Siemens_PASL_2DEPI_VB17A_BSupN_2'                   }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'                     }
    {'Siemens_PASL_2DEPI_VB17A_BSupN_2'                   }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.nii.gz'                   }
    {'Siemens_PASL_2DEPI_VB17A_BSupN_2'                   }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D_Source.json'              }
    {'Siemens_PASL_2DEPI_VB17A_BSupN_2'                   }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D_Source.nii.gz'            }
    {'Siemens_PASL_2DEPI_VB17A_BSupN_2'                   }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4Dcontext.tsv'               }
    {'Siemens_PASL_2DEPI_VB17A_BSupN_2'                   }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4Dcontext_Source.tsv'        }
    {'Siemens_PASL_2DEPI_VB17A_BSupN_2'                   }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/M0.json'                        }
    {'Siemens_PASL_2DEPI_VB17A_BSupN_2'                   }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/M0.nii.gz'                      }
    {'Siemens_PASL_2DEPI_VB17A_ADNI2_941_S_5193_1'        }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'                     }
    {'Siemens_PASL_2DEPI_VB17A_ADNI2_941_S_5193_1'        }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.nii.gz'                   }
    {'Siemens_PASL_2DEPI_VB17A_ADNI2_941_S_5193_1'        }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D_Source.json'              }
    {'Siemens_PASL_2DEPI_VB17A_ADNI2_941_S_5193_1'        }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D_Source.nii.gz'            }
    {'Siemens_PASL_2DEPI_VB17A_ADNI2_941_S_5193_1'        }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4Dcontext.tsv'               }
    {'Siemens_PASL_2DEPI_VB17A_ADNI2_941_S_5193_1'        }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4Dcontext_Source.tsv'        }
    {'Siemens_PASL_2DEPI_VB17A_ADNI2_941_S_5193_1'        }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/M0.json'                        }
    {'Siemens_PASL_2DEPI_VB17A_ADNI2_941_S_5193_1'        }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/M0.nii.gz'                      }
    {'Siemens_PASL_2DEPI_VB19A_BSupN_1'                   }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'                     }
    {'Siemens_PASL_2DEPI_VB19A_BSupN_1'                   }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.nii.gz'                   }
    {'Siemens_PASL_2DEPI_VB19A_BSupN_1'                   }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4Dcontext.tsv'               }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-101_1/ASL_1/ASL4D.json'                      }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-101_1/ASL_1/ASL4D.nii.gz'                    }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-101_1/ASL_1/ASL4Dcontext.tsv'                }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-101_1/ASL_1/M0.json'                         }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-101_1/ASL_1/M0.nii.gz'                       }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-101_1/ASL_1/M0_RevPE.json'                   }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-101_1/ASL_1/M0_RevPE.nii.gz'                 }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-101_1/ASL_2/ASL4D.json'                      }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-101_1/ASL_2/ASL4D.nii.gz'                    }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-101_1/ASL_2/ASL4Dcontext.tsv'                }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-101_1/ASL_2/M0.json'                         }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-101_1/ASL_2/M0.nii.gz'                       }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-101_1/ASL_2/M0_RevPE.json'                   }
    {'Siemens_PASL_2DEPI_VE12U_7T'                        }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-101_1/ASL_2/M0_RevPE.nii.gz'                 }
    {'Siemens_PASL_3DGRASE_VD13D_1'                       }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'                     }
    {'Siemens_PASL_3DGRASE_VD13D_1'                       }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.nii.gz'                   }
    {'Siemens_PASL_3DGRASE_VD13D_1'                       }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4Dcontext.tsv'               }
    {'Siemens_PASL_3DGRASE_VE11C_1'                       }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'                     }
    {'Siemens_PASL_3DGRASE_VE11C_1'                       }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.nii.gz'                   }
    {'Siemens_PASL_3DGRASE_VE11C_1'                       }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4Dcontext.tsv'               }
    {'Siemens_PASL_3DGRASE_VE11C_2'                       }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.json'                     }
    {'Siemens_PASL_3DGRASE_VE11C_2'                       }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4D.nii.gz'                   }
    {'Siemens_PASL_3DGRASE_VE11C_2'                       }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-Sub1_1/ASL_1/ASL4Dcontext.tsv'               }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4093_1/ASL_1/ASL4D.json'                 }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4093_1/ASL_1/ASL4D.nii.gz'               }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4093_1/ASL_1/ASL4Dcontext.tsv'           }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4093_2/ASL_1/ASL4D.json'                 }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4093_2/ASL_1/ASL4D.nii.gz'               }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4093_2/ASL_1/ASL4Dcontext.tsv'           }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4094_1/ASL_1/ASL4D.json'                 }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4094_1/ASL_1/ASL4D.nii.gz'               }
    {'Siemens_PASL_3DGRASE_VE11C_ADNI_multiSubjectSession'}    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-012S4094_1/ASL_1/ASL4Dcontext.tsv'           }
    {'Siemens_PCASL_3DGRASE_VE11C_1'                      }    {'Both'       }    {'Different file content'}    {'Different file content: /ExploreASL/sub-Sub5_1/ASL_1/M0.json'}
    {'Siemens_PCASL_multiSequence_VE11C_2'                }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_1/ASL4D.json'                     }
    {'Siemens_PCASL_multiSequence_VE11C_2'                }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_1/ASL4D.nii.gz'                   }
    {'Siemens_PCASL_multiSequence_VE11C_2'                }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_1/ASL4D_Source.json'              }
    {'Siemens_PCASL_multiSequence_VE11C_2'                }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_1/ASL4D_Source.nii.gz'            }
    {'Siemens_PCASL_multiSequence_VE11C_2'                }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_1/ASL4Dcontext.tsv'               }
    {'Siemens_PCASL_multiSequence_VE11C_2'                }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_1/ASL4Dcontext_Source.tsv'        }
    {'Siemens_PCASL_multiSequence_VE11C_2'                }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_1/M0.json'                        }
    {'Siemens_PCASL_multiSequence_VE11C_2'                }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_1/M0.nii.gz'                      }
    {'Siemens_PCASL_multiSequence_VE11C_2'                }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_2/ASL4D.json'                     }
    {'Siemens_PCASL_multiSequence_VE11C_2'                }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_2/ASL4D.nii.gz'                   }
    {'Siemens_PCASL_multiSequence_VE11C_2'                }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_2/ASL4Dcontext.tsv'               }
    {'Siemens_PCASL_multiSequence_VE11C_2'                }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_2/M0.json'                        }
    {'Siemens_PCASL_multiSequence_VE11C_2'                }    {'derivatives'}    {'Missing file'          }    {'/ExploreASL/sub-sub1_1/ASL_2/M0.nii.gz'                      }

**Pull request merged**
