### PR TITLE
Bug #589 test data jsons

### LINKED ISSUE #589: TestDataSet GM CBF low
### Description

The GM CBF calculated in TestDataSet returns a value of 0.017 in the final TSV file.

### Requirements

Test the TestDataSet execution using the DataPar.json. Verify if all DataPar.json and M0 and ASL.json are fine.

### Release notes

Fix issue with low GM CBF in TestDataSet

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

Close #589

### How to test

Run the processing of the TestDataSet and verify that the GM CBF is ~50-60ml/min/100g

### CODE REVIEW

**Comment by MichaelStritt** [comment]
```
totalGM =

  3×15 cell array

  Columns 1 through 8

    {'SUBJECT'      }    {'LongitudinalTim…'}    {'SubjectNList'}    {'Site'   }    {'GM_vol'}    {'WM_vol' }    {'CSF_vol'}    {'GM_ICVRatio' }
    {'StudyID'      }    {'integer'          }    {'integer'     }    {'integer'}    {'Liter' }    {'Liter'  }    {'Liter'  }    {'ratio GM/ICV'}
    {'sub-001_ASL_1'}    {'1'                }    {'1'           }    {'1'      }    {'0.6372'}    {'0.51224'}    {'0.43608'}    {'0.40189'     }

  Columns 9 through 15

    {'GMWM_ICVRatio'    }    {'WMH_vol'}    {'WMH_count'        }    {'MeanMotion'}    {'TotalGM_B'  }    {'TotalGM_L'  }    {'TotalGM_R'  }
    {'ratio (GM+WM)/ICV'}    {'mL'     }    {'n lesions (inte…'}    {'mm'        }    {'mL/100g/min'}    {'mL/100g/min'}    {'mL/100g/min'}
    {'0.72496'          }    {'5.062'  }    {'8'                }    {'0.034527'  }    {'52.1291'    }    {'52.4216'    }    {'51.8334'    }
```

**Review by MichaelStritt — APPROVED** [review]
👍

**Review by HenkMutsaerts — APPROVED** [review]
This is nice but we should actually remove the `derivatives/ExploreASL` and keep only `rawdata`. Does this then still work? The point is that for users it is very confusing to have both input data (`rawdata`) and output data (`derivatives/ExploreASL`). The fact that we do `BIDS2Legacy` should be behind the scenes and users should be unaware of this.
Also, is there nice feedback to the users for `BIDS2Legacy`, e.g. "Copying input data from //rawdata to //derivatives/ExploreASL" (the user shouldn't read the word "legacy" since this is quite confusing)

**Comment by MichaelStritt** [comment]
> 
> 
> This is nice but we should actually remove the `derivatives/ExploreASL` and keep only `rawdata`. Does this then still work? The point is that for users it is very confusing to have both input data (`rawdata`) and output data (`derivatives/ExploreASL`). The fact that we do `BIDS2Legacy` should be behind the scenes and users should be unaware of this.
> Also, is there nice feedback to the users for `BIDS2Legacy`, e.g. "Copying input data from //rawdata to //derivatives/ExploreASL" (the user shouldn't read the word "legacy" since this is quite confusing)

Should work and you can easily test it 👍 
Simplifying it sounds good to me.

**Comment by jan-petr** [comment]
A new branch for #589 was created based on main so that we could merge #589 as a hotfix 1.6.2
We had to create a new branch as this branch had some extra commits from version 1.7.0beta already.

**Pull request closed without merging**
