### PR TITLE
Closes #335

### LINKED ISSUE #335: Input arguments in deployed mode
Hey @jan-petr & @HenkMutsaerts,

for the compiled **xASL** version within the **docker** and the normal executable on Windows/Linux, I only used the first argument so far (the path of the DataParFile). I never needed the other options, since I wasn't using multiple workers etc. within the **docker** image. @MauricePasternak tried to use them and it didn't work. I think the problem is that you have to pass the arguments as strings from the CLI. Here is an example where they talk about that: 

> [Providing input parameters from the Windows command line to a Matlab Executable](https://stackoverflow.com/questions/14431370/providing-input-parameters-from-the-windows-command-line-to-a-matlab-function-co)

> When you run the executable from the [...] command line, the arguments get passed in to the executable as strings ...

I think the most straight forward solution would be to do this in `line 54` and following in `ExploreASL_Master`:

```
if isdeployed
    if nargin > 1 && ~isempty(ProcessData)
        ProcessData = str2num(ProcessData);
    end
    if nargin > 2 && ~isempty(SkipPause)
        SkipPause= str2num(SkipPause);
    end
    if nargin > 2 && ~isempty(iWorker)
        iWorker= str2num(iWorker);
    end
    if nargin > 2 && ~isempty(nWorkers)
        nWorkers= str2num(nWorkers);
    end
    if nargin > 2 && ~isempty(iModules)
        iModules= str2num(iModules);
    end
end
```

Would this be okay?

Then you could call the executable like this e.g.:

```
xASL_1_4_0.exe "c:\path_to_your\DataParFile.json" "1" "1"
```

### PR DESCRIPTION
**Pull request by MichaelStritt**
Hey @HenkMutsaerts, this should fix #335. Check out my test results in the #355 comments. Tested on windows & linux in compiled and normal mode.

Edit: @MauricePasternak this should fix the bugs you encountered. If everything's going as planned, we'll release this weekend, then you can try it with the compiled v1.5.0 version.

### CODE REVIEW

**Review by HenkMutsaerts — CHANGES_REQUESTED** [review]
Looks very good!

I would remove the `isdeployed` condition, again, to go with "generalization/transparent programming", I would keep the input arguments the same with and without deployment, if we can.

If you add `xASL_str2num`, this should allow both strings and numbers as input, regardless if you are running deployed or not.

**Comment by MichaelStritt** [comment]
> I would remove the isdeployed condition, again, to go with "generalization/transparent programming", I would keep the input arguments the same with and without deployment, if we can.

I tried that, but Matlab raises an error (it expects strings if you use `str2num`).

**Comment by MichaelStritt** [comment]
### str2num replaced by xASL_str2num

```
>> [x] = ExploreASL_Master('', 0, 1, 1, 1, [1 2 3]);
--> Initializing ExploreASL v1.4.0...
==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  
==============================================================================================
ExploreASL initialized <--
>> x
x = 
  struct with fields:
                     nWorkers: 1
                      iWorker: 1
...
```


```
>> [x] = ExploreASL_Master("", "0", "1", "1", "1", "[1 2 3]");
--> Initializing ExploreASL v1.4.0...
==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  
==============================================================================================
ExploreASL initialized <--
>> x
x = 
  struct with fields:
                     nWorkers: 1
                      iWorker: 1
...
```

Behavior seems to be robust 👍

**Review by HenkMutsaerts — APPROVED** [review]
I did some changes to use ExploreASL code (has some advantages) and some code debulking, but essentially no functionality change.

I only added some additional `iModules` parsing, in case the concatenation of strings goes wrong.

Though just detected that the xASL code isn't loaded as ExploreASL isn't initialized only later in the code :( so reverted my xASL_str2num to str2num:)

Now tested without deployment, needs testing when deployed.

**Comment by MichaelStritt** [comment]
> I only added some additional `iModules` parsing, in case the concatenation of strings goes wrong.

See #335. This definitely didn't work and shouldn't be necessary.

> Though just detected that the xASL code isn't loaded as ExploreASL isn't initialized only later in the code :( so reverted my xASL_str2num to str2num:)

In compiled mode this shouldn't be a problem. As far as I understood, everything you add using mcc(...) is a known path for the script. But you're right, in not deployed mode this could raise an error. I only see the option of doing it like in 87d878e & 
77472c9 or to use isstring.

> Now tested without deployment, needs testing when deployed.

It definitely didn't work, even without deployment (if you were to insert strings).
If it doesn't need to work for strings in not-deployed mode we can just use isdeployed as initially proposed.

**Comment by MichaelStritt** [comment]
## Matlab

```
>> [x] = ExploreASL_Master('', 0, 1, 1, 1, [1 2 3]);
94      x = ExploreASL_Initialize(DataParPath, ProcessData, iWorker, nWorkers);
K>> ProcessData
ProcessData =
     0
K>> iWorker
iWorker =
     1
K>> nWorkers
nWorkers =
     1
K>> iModules
iModules =
     1     2     3
```

```
>> [x] = ExploreASL_Master("", "0", "1", "1", "1", "[1 2 3]");
94      x = ExploreASL_Initialize(DataParPath, ProcessData, iWorker, nWorkers);
K>> ProcessData
ProcessData =
     0
K>> iWorker
iWorker =
     1
K>> nWorkers
nWorkers =
     1
K>> iModules
iModules =
     1     2     3
```

**Comment by MichaelStritt** [comment]
## Windows compiled

```
.\xASL_latest>xASL_latest.exe "" "0"
Warning: Invalid input argument "ProcessData", should be 0, 1, or 2, resetting
> In ExploreASL_Initialize (line 80)
  In ExploreASL_Master (line 94)
Would you like to load a dataset or only initialize ExploreASL (set paths etc)?
Please press [1] for "Process dataset", [2] for "Only initialize ExploreASL functionality", 
[3] for "Load dataset only", or [4] to cancel: 0
Wrong choice, please choose 1 2, 3, or 4: Reference to non-existent field 'ProcessData'.
Error in ExploreASL_Master (line 96)
MATLAB:nonExistentField
```

Hmm... I'm not sure, but I think `ispc` could be the problem. I'll try it without that.

**Comment by MichaelStritt** [comment]
This doesn't work either, maybe we have to use isdeployed after all... But I don't see any disadvantages if we do so?

```
.\xASL_latest>xASL_latest.exe "" "0" "1" "1" "1"
Warning: Could not get change notification handle for .\xASL_latest_mcr\toolbox\local.
Type 'help changeNotification' for more info.
Warning: argin "nWorkers" should be numerical, using default==1
> In ExploreASL_Initialize (line 54)
  In ExploreASL_Master (line 94)
Warning: argin "iWorker" should be numerical, using default==1
> In ExploreASL_Initialize (line 61)
  In ExploreASL_Master (line 94)
Warning: Invalid input argument "ProcessData", should be 0, 1, or 2, resetting
> In ExploreASL_Initialize (line 80)
  In ExploreASL_Master (line 94)
Would you like to load a dataset or only initialize ExploreASL (set paths etc)?
```

**Comment by MichaelStritt** [comment]
## Compiled

```
.\xASL_latest>xASL_latest.exe "" "0" "1" "1" "1" "[1 2 3]"
==============================================================================================
ctfroot:  .\xASL_latest\xASL_latest_mcr
x.MyPath: .\xASL_latest\xASL_latest_mcr\xASL_latest
==============================================================================================
 ___  ____  __  __
/ __)(  _ \(  \/  )  modified xASL version
\__ \ )___/ )    (   Statistical Parametric Mapping
(___/(__)  (_/\/\_)  SPM12 - http://www.fil.ion.ucl.ac.uk/spm/

--> Initializing ExploreASL v1.4.0...


==============================================================================================
 ________                      __                                 ______    ______   __
/        |                    /  |                               /      \  /      \ /  |
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/
                    ## |
                    ## |
                    ##/
==============================================================================================


ExploreASL initialized <--
```


```
.\xASL_latest>xASL_latest.exe ".\Test_Runs\TestDataSet\analysis\DataParameters_LowQ.json" "1" "1" "1" "1" "[1 2 3]"
==============================================================================================
ctfroot:  .\xASL_latest\xASL_latest_mcr
x.MyPath: .\xASL_latest_mcr\xASL_latest
==============================================================================================
 ___  ____  __  __
/ __)(  _ \(  \/  )  modified xASL version
\__ \ )___/ )    (   Statistical Parametric Mapping
(___/(__)  (_/\/\_)  SPM12 - http://www.fil.ion.ucl.ac.uk/spm/

--> Initializing ExploreASL v1.4.0...


==============================================================================================
 ________                      __                                 ______    ______   __
/        |                    /  |                               /      \  /      \ /  |
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/
                    ## |
                    ## |
                    ##/
==============================================================================================


ExploreASL initialized <--
Automatically defining sessions...
-------------------------------------------
ExploreASL will run with following settings:

Root folder = .\TestDataSet\analysis

1 scans - 0 exclusions, resulting in 1 scans of:
Longitudinal timePoint 1 = 1 scans - 0 exclusions = 1 scans
ASL sessions: 1

Ancillary data, sets:
3 sets are defined for 1 "SubjectsSessions":
Set 1 = "LongitudinalTimePoint" options "TimePoint_1", codes for paired data
Set 2 = "SubjectNList" options "SubjectNList", codes for paired data
Set 3 = "Site" options "SingleSite", codes for two-sample data
x.DELETETEMP = 1 (delete temporary files)
x.Quality    = 0 (0 = fast try-out; 1 = normal high quality)

---------------------------------------------


Running xASL_module_Structural ...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

**Pull request merged**
