### PR TITLE
Closes #959 Hadamard import FME

### LINKED ISSUE #959: Bremen Hadamard import and initialization
### Description

Several issues to be fixed:
- `EchoNumber` DICOM tag should not go to BIDS. c3c2631 :+1: 
- `TimeEncodedEchoTimes` is correctly calculated and needed for processing and QA, but should not be saved to BIDS. I thus propose to make a new function to calculate it centrally and move the code from `xASL_bids_BIDSifyCheckTimeEncoded.m` to it. Then still call this new function from there as we need it to calculate the number of repetitions. But then not save it to BIDS or Legacy, but recalculate again in xASL_module. The only reason being that this variable can easily be obtained from the TE vector and will thus probably not make it into the BIDS definition once Hadamard is included. Also, this should be renamed to `NumberEchoTimes` as it is a general parameter. 2db00c4 :+1: 
- TotalAcquired pairs should refer to number of repetitions = full pairs C/L or full set of Hadamard matrix. 604b0af :+1: 
- Lastly, `TimeEncodedMatrixType`, `TimeEncodedMatrixSize`, `NumberEchoTimes` should go to x.Q. And only bMultiTE etc should stay in x.modules.asl. 0662f7b :+1: 
- Rename DecodingMatrix to TimeEncodedMatrix and fix the call of `xASL_quant_HadamardDecoding` so that we pass x.Q field and not some xDecoding field that might sound unclear. a45bf7a :+1: 

### Release notes

Removed EchoNumber and TimeEncodedEchoTimes fields from BIDS and optimized Hadamard import and initialization.

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

#959

### CODE REVIEW

**Review by MichaelStritt — APPROVED** [review]
Really nice changes, they nicely clean up Beatriz' code

**Comment by MichaelStritt** [comment]
Running the flavors now

**Comment by MichaelStritt** [comment]
So I updated the flavors and ran everything (without the processing) again. Is it possible that this is an os related defect?

```
COMPARISON TABLE:
                       flavor                               dataset                      name                                            message                              
    _____________________________________________    ______________________    ________________________    ___________________________________________________________________

    'Siemens_PCASL_3DGRASE_VD13A_Hadamard4-FME_1'    'rawdata'                 'Missing file'              '\sub-Sub1\perf\sub-Sub1_asl.json'                                 
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard4-FME_1'    'rawdata'                 'Missing file'              '\sub-Sub1\perf\sub-Sub1_asl.nii.gz'                               
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard4-FME_1'    'rawdata'                 'Missing file'              '\sub-Sub1\perf\sub-Sub1_aslcontext.tsv'                           
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard4-FME_1'    'rawdata'                 'Missing file'              '\sub-Sub1\perf\sub-Sub1_m0scan.json'                              
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard4-FME_1'    'rawdata'                 'Missing file'              '\sub-Sub1\perf\sub-Sub1_m0scan.nii.gz'                            
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard8-FME_1'    'rawdata'                 'Missing file'              '\sub-Sub1\perf\sub-Sub1_asl.json'                                 
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard8-FME_1'    'rawdata'                 'Missing file'              '\sub-Sub1\perf\sub-Sub1_asl.nii.gz'                               
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard8-FME_1'    'rawdata'                 'Missing file'              '\sub-Sub1\perf\sub-Sub1_aslcontext.tsv'                           
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard8-FME_1'    'rawdata'                 'Missing file'              '\sub-Sub1\perf\sub-Sub1_m0scan.json'                              
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard8-FME_1'    'rawdata'                 'Missing file'              '\sub-Sub1\perf\sub-Sub1_m0scan.nii.gz'                            
    'Philips_PCASL_2DEPI_3.2.2.1_2'                  'Both'                    'Different file content'    'Different file content: \ExploreASL\dataset_description.json'     
    'Philips_PCASL_2DEPI_3.2.2.1_2'                  'Both'                    'Different file content'    'Different file content: \ExploreASL\sub-ABC301_1\ASL_1\ASL4D.json'
    'Philips_PCASL_2DEPI_3.2.2.1_2'                  'Both'                    'Different file content'    'Different file content: \ExploreASL\sub-ABC301_1\ASL_1\M0.json'   
    'Philips_PCASL_2DEPI_3.2.2.1_2'                  'Both'                    'Different file content'    'Different file content: \ExploreASL\sub-ABC301_1\FLAIR.json'      
    'Philips_PCASL_2DEPI_3.2.2.1_2'                  'Both'                    'Different file content'    'Different file content: \ExploreASL\sub-ABC301_1\T1.json'         
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard4-FME_1'    'derivativesReference'    'Missing folder'            '\ExploreASL\temp'                                                 
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard4-FME_1'    'derivatives'             'Missing folder'            '\ExploreASL\sub-Sub1_1\ASL_1'                                     
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard4-FME_1'    'derivativesReference'    'Missing file'              '\ExploreASL\temp\dcm2niiCatchedErrors.json'                       
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard4-FME_1'    'derivativesReference'    'Missing file'              '\ExploreASL\temp\dcm2niiCatchedErrors.mat'                        
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard4-FME_1'    'derivatives'             'Missing file'              '\ExploreASL\sub-Sub1_1\ASL_1\ASL4D.json'                          
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard4-FME_1'    'derivatives'             'Missing file'              '\ExploreASL\sub-Sub1_1\ASL_1\ASL4D.nii.gz'                        
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard4-FME_1'    'derivatives'             'Missing file'              '\ExploreASL\sub-Sub1_1\ASL_1\ASL4D_aslcontext.tsv'                
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard4-FME_1'    'derivatives'             'Missing file'              '\ExploreASL\sub-Sub1_1\ASL_1\M0.json'                             
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard4-FME_1'    'derivatives'             'Missing file'              '\ExploreASL\sub-Sub1_1\ASL_1\M0.nii.gz'                           
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard8-FME_1'    'derivativesReference'    'Missing folder'            '\ExploreASL\temp'                                                 
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard8-FME_1'    'derivatives'             'Missing folder'            '\ExploreASL\sub-Sub1_1\ASL_1'                                     
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard8-FME_1'    'derivativesReference'    'Missing file'              '\ExploreASL\temp\dcm2niiCatchedErrors.json'                       
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard8-FME_1'    'derivativesReference'    'Missing file'              '\ExploreASL\temp\dcm2niiCatchedErrors.mat'                        
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard8-FME_1'    'derivatives'             'Missing file'              '\ExploreASL\sub-Sub1_1\ASL_1\ASL4D.json'                          
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard8-FME_1'    'derivatives'             'Missing file'              '\ExploreASL\sub-Sub1_1\ASL_1\ASL4D.nii.gz'                        
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard8-FME_1'    'derivatives'             'Missing file'              '\ExploreASL\sub-Sub1_1\ASL_1\ASL4D_aslcontext.tsv'                
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard8-FME_1'    'derivatives'             'Missing file'              '\ExploreASL\sub-Sub1_1\ASL_1\M0.json'                             
    'Siemens_PCASL_3DGRASE_VD13A_Hadamard8-FME_1'    'derivatives'             'Missing file'              '\ExploreASL\sub-Sub1_1\ASL_1\M0.nii.gz'                           

LOGGING TABLE:

```

**Review by MDijsselhof — APPROVED** [review]
Looks good to me!

**Review by BeatrizPadrela — APPROVED** [review]
Great changes, looks very nice!

**Pull request merged**
