### PR TITLE
#591 multiTE import - taking TE first then PLD

### PR DESCRIPTION
**Pull request by jan-petr**
### Linked issue

#591 

### How to test

Import DEBBIE data of hadamard 4 and 8. Make sure the order in both image and JSON is first TE then PLD.

### CODE REVIEW

**Comment by MichaelStritt** [comment]
@BeatrizPadrela: I think you have the data access, right? Can you run a small test?

**Comment by BeatrizPadrela** [comment]
> @BeatrizPadrela: I think you have the data access, right? Can you run a small test?

Sure, will do now!

**Comment by BeatrizPadrela** [comment]
image

the vectorOldOrder seems to be okay
But @jan-petr  this printscreen is from asl.json. Shouldn't the PLD vector be [1,1,1,1,1,1,1,1,1,2,2,2,2,]?

**Comment by jan-petr** [comment]
> image
> 
> the vectorOldOrder seems to be okay
> But @jan-petr this printscreen is from asl.json. Shouldn't the PLD vector be [1,1,1,1,1,1,1,1,1,2,2,2,2,]?

Thanks. Trivial mistake. Fixed.

**Review by MichaelStritt — APPROVED** [review]
👍

**Comment by MichaelStritt** [comment]
@BeatrizPadrela: After this is merged, we could update the rawdata & derivatives folders in the FME sequence repository, so that it's easier for @amahroo and you to work with it.

**Comment by jan-petr** [comment]
> @BeatrizPadrela: After this is merged, we could update the rawdata & derivatives folders in the FME sequence repository, so that it's easier for @amahroo and you to work with it.

Yes. That would be good. @BeatrizPadrela can you check if this is fine now for both had4 and had8 and approve. I'll merge it then. Thanks.

**Comment by MichaelStritt** [comment]
> 
> 
> > @BeatrizPadrela: After this is merged, we could update the rawdata & derivatives folders in the FME sequence repository, so that it's easier for @amahroo and you to work with it.
> 
> Yes. That would be good. @BeatrizPadrela can you check if this is fine now for both had4 and had8 and approve. I'll merge it then. Thanks.

We could also think about adding one Hadamard-4 and one Hadamard-8 case to the flavor database. I think we even talked about it with Amnah before, right?

**Comment by BeatrizPadrela** [comment]
> > > @BeatrizPadrela: After this is merged, we could update the rawdata & derivatives folders in the FME sequence repository, so that it's easier for @amahroo and you to work with it.
> > 
> > 
> > Yes. That would be good. @BeatrizPadrela can you check if this is fine now for both had4 and had8 and approve. I'll merge it then. Thanks.
> 
> We could also think about adding one Hadamard-4 and one Hadamard-8 case to the flavor database. I think we even talked about it with Amnah before, right?

That's a good idea Michael. I will now test this so we can merge

**Comment by BeatrizPadrela** [comment]
So for Hadamard-4 everything works!

Now I'm trying to get Hadamard-8 data to test this. @MichaelStritt  do you know how to sort the dicoms into two folders  of ASL and M0? (like you did for Hadamard-4)

**Comment by MichaelStritt** [comment]
@BeatrizPadrela & @jan-petr: I've added a Hadamard-4 and a Hadamard-8 case to the flavor library. I don't think the Hadamard-8 does work properly yet. The echo times and the PLDs in the asl.json aren't correct. Maybe it is required to check if the regular expressions work correctly.

**Comment by BeatrizPadrela** [comment]
Yes, I also ran the import for Hadamard-8 and the ASL.json looks like this:
image

@MichaelStritt  maybe we can fix this in this issue, or do you think that creating other issue is advantageous?

**Comment by jan-petr** [comment]
I would fix it inside this issue already. And make sure that it works on both flavors. Will do that quickly...

**Comment by MichaelStritt** [comment]
I just reran it. It has to be fixed either in `xASL_imp_NII2BIDS_SubjectSessionRun` or in `xASL_imp_DCM2NII_Subject_ShuffleTheDynamics`... I think. The regular expression seems to work just fine in both cases.

**Comment by MichaelStritt** [comment]
So here we have for Hadamard-4 3 TIs and 8 TEs. For Hadamard-8 we have 7 TIs and 1 TE.

**Comment by jan-petr** [comment]
Fixed. Pull a new version of Flavors. The number of PLDs and HadamardMatrix was set incorrectly. This is now fixed in the references..

**Pull request merged**
