### PR TITLE
Closes #1712 SubjectWiseMaskPrinting

### LINKED ISSUE #1712: Subject-wise mask and atlas printing error
### Description

The boolean `x.S.SubjectWiseVisualizations` can be enabled to print the final ROIs/masks per subject (after all atlas & subject-wise masks have been combined, e.g., deep WM + vascular mask + FoV mask + pvWM), in the map `/Population/Stats/CheckMasksVisually`. 

There was a bug that needed fixing, and not all masks were shown.
Note that some of the changes below will be changed more later, if we remove some of the im2column.

### Tasks

- [x] Move xASL_Convert3D_4D_atlas (& 4D_3D_atlas) outside functions `xASL_stat_GetROIStatistics` & `xASL_stat_AtlasForStats` (needed for both)
- [x] xASL_stat_GetROIStatistics: add visualization to multiple locations

### How to test

Can be tested on flux: lood_storage/divi/Projects/ExploreASL/insight46/derivatives/ExploreASL/

### Release notes

Print subject-wise mask visualizations.

### PR DESCRIPTION
**Pull request by HenkMutsaerts**
### Linked issue

Closes #1712

### CODE REVIEW

**Review by jan-petr — CHANGES_REQUESTED** [review]
Looks good so far. Needs more work to finalize the PMs. And needs to be sharp tested by Mathijs that it works fine.

**Review by MDijsselhof — CHANGES_REQUESTED** [review]
Looks good, but the images printed with _CBF or _sCoV at the end only show one hemisphere.

**Comment by HenkMutsaerts** [comment]
I now fixed this such that we only show the bilateral ROI: 8ebaf504e776373dd94d66853b1cae3b86b1da35. Also, I added a functionality to use custom atlases if the user added this to the ExploreASL/External/Atlases folder (this is what the EPOD team did, this is probably OK as this is our default atlas location anyway): e4f50644aa1472f04af554096d969db25d8ff25e.

**Review by jan-petr — CHANGES_REQUESTED** [review]
#1712 - I am fine to merge this with two questions.
1.⁠ ⁠Mathijs tested it, found a bug and you fixed it. Your responsibility to say that it doesn’t need more testing. 
2.⁠ ⁠⁠There are several comments like “% PM: REPLACE WITH xASL_vis_CreateVisualFig”. Do you plan to do these in the future? If yes, please make sure that a new issue is created and planned.

**Review by jan-petr — APPROVED** [review]
OK

**Review by MDijsselhof — APPROVED** [review]

**Pull request merged**
