### PR TITLE
Update xASL_adm_GzipNifti.m

### PR DESCRIPTION
**Pull request by HenkMutsaerts**
Minor bugfix

### CODE REVIEW

**Comment by jan-petr** [comment]
You introduced a bug. I have fixed it in my recent commit. See if this is still fine and then we can approve this.

**Comment by jan-petr** [comment]
See my commit here. Unfortunately, I couldn't relate it to this branch since there was no issue associated!
https://github.com/ExploreASL/ExploreASL/commit/acd465a2ad3f600b4f1c33b112e8ba8a2d041eef

**Comment by jan-petr** [comment]
No, you have introduced a bug with your bugfix, so I had to revert it :D

if isGz == 1
then the file is file.nii.gz and name0 = file.nii
so I put breakpoint in the code and your fix created file.nii.nii

**Comment by jan-petr** [comment]
xASL_fileparts and fileparts behave differently!!!

[path0,name0,~] = xASL_fileparts('/test/test/test.nii.gz')

path0 =

    '/test/test'


name0 =

    'test'

>> [path0,name0,~] = fileparts('/test/test/test.nii.gz')

path0 =

    '/test/test'


name0 =

    'test.nii'

**Comment by HenkMutsaerts** [comment]
Ah OK, you're right. Then we can revert my change, and add the comment that this had the .nii (just that I won't complain about it later ;) Then we can squash & merge (or rebase? ;)

You want to do this or shall I do this?

**Comment by jan-petr** [comment]
I would not revert - it fixed other good things. I would keep as it is now - after my last fix, all is good.

Regarding merging - I would do squash in this case - it was a really minor edit, so we don't need to have the long list of comments in between.

**Pull request merged**
