### PR TITLE
Bug #228 cat12 warnings

### LINKED ISSUE #228: CAT12 warnings - Non-existent field cm
[CAT12 Failure - Non-existent field cm.txt](https://github.com/ExploreASL/ExploreASL/files/5555646/CAT12.Failure.-.Non-existent.field.cm.txt)

Furthermore, the program attempts to re-start CAT12 but enters into some sort of infinite loop. A SIGKILL signal does not stop it.

### PR DESCRIPTION
**Pull request by HenkMutsaerts**
Closes #228

### CODE REVIEW

**Review by jan-petr — APPROVED** [review]
Looks good.

**Review by MauricePasternak — DISMISSED** [review]
I concur. Generally proceeds without any major error.

**Comment by HenkMutsaerts** [comment]
@MDijsselhof You want to merge this for practice? You could do this together with Beatriz, for her to get some practice.

**Review by MichaelStritt — APPROVED** [review]

**Review by jan-petr — APPROVED** [review]
OK.

**Pull request merged**
