### PR TITLE
Bug #483 major test and debug

### PR DESCRIPTION
**Pull request by jan-petr**
Columns 1 through 7

    {'Data'             }    {'mean_qCBF_TotalGM'}    {'median_qCBF_Tot…'}    {'median_qCBF_Dee…'}    {'CoV_qCBF_TotalGM'}    {'GMvol' }    {'WMvol' }
    {'GE_3Dspiral_T1p…'}    {'65.2563'          }    {'52.5036'          }    {'31.8919'          }    {'0.29791'         }    {[0.6399]}    {[0.5052]}
    {'Philips_2DEPI_F…'}    {'39.3939'          }    {'27.8202'          }    {'6.6509'           }    {'0.71154'         }    {[0.5349]}    {[0.4590]}
    {'Philips_2DEPI_F…'}    {'41.4568'          }    {'31.8538'          }    {'13.8988'          }    {'0.37713'         }    {[0.5442]}    {[0.3921]}
    {'Philips_2DEPI_F…'}    {'47.3009'          }    {'42.3166'          }    {'20.0262'          }    {'0.43007'         }    {[0.6994]}    {[0.5816]}
    {'Philips_2DEPI_L…'}    {'8.1481'           }    {'14.172'           }    {'2.9897'           }    {'0.89531'         }    {[0.7099]}    {[0.5136]}
    {'Philips_2DEPI_S…'}    {'45.7118'          }    {'41.0417'          }    {'9.5548'           }    {'0.36756'         }    {[0.8167]}    {[0.4596]}
    {'Philips_3DGRASE…'}    {'35.2728'          }    {'26.2953'          }    {'7.5123'           }    {'0.6423'          }    {[0.5709]}    {[0.5279]}
    {'Philips_3DGRASE…'}    {'32.1226'          }    {'24.2851'          }    {'8.5947'           }    {'0.43015'         }    {[0.7239]}    {[0.5520]}
    {'Siemens3DGRASE_…'}    {'37.6934'          }    {'37.2872'          }    {'21.7901'          }    {'0.78873'         }    {[0.5191]}    {[0.4658]}
    {'Siemens_2DEPI_n…'}    {'67.5268'          }    {'50.6621'          }    {'13.4265'          }    {'0.31694'         }    {[0.6887]}    {[0.6031]}

  Columns 8 through 11

    {'CSFvol'}    {'PipelineCompleted'}    {'TC_ASL_Registra…'}    {'TC_M0_Registrat…'}
    {[0.4329]}    {[                1]}    {[           0.9015]}    {[           0.9315]}
    {[0.4056]}    {[                1]}    {[           0.7300]}    {[           0.8166]}
    {[0.3564]}    {[                1]}    {[           0.9017]}    {[           0.9478]}
    {[0.2222]}    {[                1]}    {[           0.8136]}    {[           0.8453]}
    {[0.1939]}    {[                1]}    {[           0.7593]}    {[           0.8910]}
    {[0.1516]}    {[                1]}    {[           0.8539]}    {[           0.8047]}
    {[0.4220]}    {[                1]}    {[           0.8581]}    {[           0.7544]}
    {[0.3564]}    {[                1]}    {[           0.8418]}    {[           0.8938]}
    {[0.4054]}    {[                1]}    {[           0.6915]}    {[           0.4987]}
    {[0.3101]}    {[                1]}    {[           0.8758]}    {[           0.9589]}

### CODE REVIEW

**Comment by jan-petr** [comment]
Current status.
10 TestDataset run without errors - results above - need to be checked.
Flavors - DCM2BIDS and BIDS2Legacy works, but some minor errors are still in the processing of those - working on that.

It would be good if @HenkMutsaerts could check the results above. And @MichaelStritt could test everything Test+Flavors+Unit on Windows. And I will fix the Flavors processing

**Comment by jan-petr** [comment]
Flavors processing (but note that not all has to be fine since not all sets might be correctly configured - it always has to be determined if this is a bug or mistake in data)

- All GE is fine
- Philips_PCASL_2DEPI_Ingenia_volunteer, Philips_PCASL_2DEPI_dummyLL, Philips_PCASL_2DEPI_dummyMultiPLD, Philips_PCASL_2DEPI_dummyQUASAR, Philips_PCASL_3DGRASE_R5.4_TopUp crash

**Comment by MichaelStritt** [comment]
> Current status.
> 10 TestDataset run without errors - results above - need to be checked.
> Flavors - DCM2BIDS and BIDS2Legacy works, but some minor errors are still in the processing of those - working on that.
> 
> It would be good if @HenkMutsaerts could check the results above. And @MichaelStritt could test everything Test+Flavors+Unit on Windows. And I will fix the Flavors processing

I can start the tests now and will post the results in a few hours 👍

**Comment by MichaelStritt** [comment]
### Unit Testing

```matlab
================================= TEST RESULTS =================================

              name                  unit          tests        passed
    _________________________    __________    ____________    ______

    'xASL_bids_BIDS2Legacy'      'Function'    [1×2 struct]    true  
    'ExploreASL_Master'          'Function'    [1×4 struct]    true  
    'xASL_io_ExportVTK'          'Function'    [1×5 struct]    true  
    'xASL_test_GetLogContent'    'Function'    [1×2 struct]    true  
    'xASL_io_Nifti2Im'           'Function'    [1×1 struct]    true  
    'xASL_tsvRead'               'Function'    [1×2 struct]    true  
    'xASL_tsvWrite'              'Function'    [1×2 struct]    true  

================================================================================
```

**Review by HenkMutsaerts — APPROVED** [review]

**Comment by MichaelStritt** [comment]
### BIDS_fullPipelineTest

```
ExploreASL will run the initialization...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath				
Import Modules			   
Process Modules			  
bPause					0
iWorker					1
nWorkers				1
==============================================================================================
ExploreASL v1.5.1 initialized ... 
Copying the source data to a temporary folder: .\TestBIDS\TmpConversion
Copying:  100%
Copying the BIDS reference data to a temporary folder: .\TestBIDS\TmpReference100%
ExploreASL will run the initialization...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath				
Import Modules			   
Process Modules			  
bPause					0
iWorker					1
nWorkers				1
==============================================================================================
ExploreASL v1.5.1 initialized ... 
ExploreASL will run the initialization...


==============================================================================================
 ________                      __                                 ______    ______   __        
/        |                    /  |                               /      \  /      \ /  |      
########/  __    __   ______  ## |  ______    ______    ______  /######  |/######  |## |      
## |__    /  \  /  | /      \ ## | /      \  /      \  /      \ ## |__## |## \__##/ ## |      
##    |   ##  \/##/ /######  |## |/######  |/######  |/######  |##    ## |##      \ ## |      
#####/     ##  ##<  ## |  ## |## |## |  ## |## |  ##/ ##    ## |######## | ######  |## |      
## |_____  /####  \ ## |__## |## |## \__## |## |      ########/ ## |  ## |/  \__## |## |_____ 
##       |/##/ ##  |##    ##/ ## |##    ##/ ## |      ##       |## |  ## |##    ##/ ##       |
########/ ##/   ##/ #######/  ##/  ######/  ##/        #######/ ##/   ##/  ######/  ########/ 
                    ## |                                                                      
                    ## |                                                                      
                    ##/  

==================================== ExploreASL Settings =====================================
DataParPath				
Import Modules			   
Process Modules			  
bPause					0
iWorker					1
nWorkers				1
==============================================================================================
ExploreASL v1.5.1 initialized ... 
Warning: No matching files, skipping 
> In ExploreASL_ImportBIDS>ExploreASL_ImportBIDS_DCM2NII (line 1103)
  In ExploreASL_ImportBIDS (line 278)
  In xASL_test_BIDSConversion (line 66)
  In xASL_test_BIDSFlavorsFull (line 107)
  In BIDS_fullPipelineTest (line 67) 
dataset_description.json is missing the following RECOMMENDED fields: 
HEDVersion
Warning: No matching files, skipping 
> In ExploreASL_ImportBIDS>ExploreASL_ImportBIDS_DCM2NII (line 1103)
  In ExploreASL_ImportBIDS (line 278)
  In xASL_test_BIDSConversion (line 66)
  In xASL_test_BIDSFlavorsFull (line 107)
  In BIDS_fullPipelineTest (line 67) 
dataset_description.json is missing the following RECOMMENDED fields: 
HEDVersion, DatasetType, License
Warning: No matching files, skipping 
> In ExploreASL_ImportBIDS>ExploreASL_ImportBIDS_DCM2NII (line 1103)
  In ExploreASL_ImportBIDS (line 278)
  In xASL_test_BIDSConversion (line 66)
  In xASL_test_BIDSFlavorsFull (line 107)
  In BIDS_fullPipelineTest (line 67) 
...
```

Do you have the same bug in the fullPipeline Test?

**Comment by MichaelStritt** [comment]
Hm... I think the `Sub1` folder should be within the `sourcedata` folder instead, right?

Since we have:

```
>> imPar.RawRoot
    '.\TestBIDS\TmpConversion\GE_PCASL_2DEPI_volunteer\sourcedata'
>> imPar.folderHierarchy
    {'^(.)+$'                 }
    {'^(ASL|T1w|M0|T2|FLAIR)$'}
```

image

**Comment by HenkMutsaerts** [comment]
This is my results from xASL_qc_TestExploreASL on the AMC Flux server after 7a59589


    'Data'                   'mean_qCBF_TotalGM'    'median_qCBF_TotalGM'    'median_qCBF_DeepWM'    'CoV_qCBF_TotalGM'    'GMvol'     'WMvol'     'CSFvol'    'PipelineCompleted'    'TC_ASL_Registration'
    'GE_3Dspiral_T1pre…'    '65.5445'              '52.7045'                '31.9763'               '0.29857'             [0.6400]    [0.5054]    [0.4330]    [                1]    [             0.9006]
    'Philips_2DEPI_FEA…'    '39.0998'              '27.6397'                '6.6898'                '0.71278'             [0.5349]    [0.4590]    [0.4056]    [                1]    [             0.7298]
    'Philips_2DEPI_FLA…'    '41.5598'              '31.8081'                '13.8724'               '0.37772'             [0.5442]    [0.3920]    [0.3561]    [                1]    [             0.9022]
    'Philips_2DEPI_FLA…'    '47.2791'              '42.3023'                '20.0151'               '0.43006'             [0.6994]    [0.5816]    [0.2222]    [                1]    [             0.8136]
    'Philips_2DEPI_Les…'    '8.1484'               '14.1728'                '2.9913'                '0.89536'             [0.7096]    [0.5136]    [0.1942]    [                1]    [             0.7593]
    'Philips_2DEPI_Seg…'    '45.7307'              '41.0665'                '9.5363'                '0.36767'             [0.8167]    [0.4596]    [0.1516]    [                1]    [             0.8539]
    'Philips_3DGRASE_F…'    '35.2494'              '26.2822'                '7.4964'                '0.64472'             [0.5716]    [0.5282]    [0.4207]    [                1]    [             0.8579]
    'Philips_3DGRASE_M…'    '32.0096'              '24.2742'                '8.5359'                '0.43319'             [0.7239]    [0.5520]    [0.3564]    [                1]    [             0.8407]
    'Siemens3DGRASE_St…'    '37.6957'              '37.2872'                '21.7901'               '0.78873'             [0.5191]    [0.4658]    [0.4054]    [                1]    [             0.6915]
    'Siemens_2DEPI_noB…'    '67.5016'              '50.6498'                '13.4243'               '0.31698'             [0.6886]    [0.6030]    [0.3101]    [                1]    [             0.8757]

  Column 11

    'TC_M0_Registration'
    [            0.9336]
    [            0.8159]
    [            0.9478]
    [            0.8453]
    [            0.8911]
    [            0.8044]
    [            0.7543]
    [            0.8937]
    [            0.4987]
    [            0.9589]

**Review by MichaelStritt — APPROVED** [review]
Let's merge 👍

**Comment by jan-petr** [comment]
> Yes, this is good. But you also want another case, which is why I would use the fileparts() instead of the /* fix that you did.
> 
> See example 2 that I wrote above, where the copied filename has no extension and its name is identical to an already existing foldername.
> 
> In other words, you can replace your fix by the following fix:
> 
> `[~, SrcFile] = fileparts(SrcPath);`
> `[~, DstFile] = fileparts(DstPath);`
> `if strcmp(SrcFile, DstFile)==1 && isunix()==1`
> `.... DstPath = fileparts(DstPath);`
> `end`

Cannot happen. You cannot have a filename without extension (and with extension either) that has a name equal to a directory name. Directory and a file are one and the same entity under Linux - just different in properties.

**Review by HenkMutsaerts — APPROVED** [review]

**Pull request merged**
