### PR TITLE
Closes #685 changed template names

### LINKED ISSUE #685: Template abbreviation dataPar.json mismatch
### Description

Currently the filenames for different templates used in the Population module for ROI analyses do not always match the corresponding names used inside xASL. Although the corresponding functions work, the names should be changed to match and be more intuitive.

### Requirements

All template filenames should match the internal xASL names.

### Release notes

Correct names of atlases.

### PR DESCRIPTION
**Pull request by MDijsselhof**
### Linked issue

Closes #685 

### How to test

Required: if not defined in the linked issue, add a simple test description here

### Comments

Optional: add helpful comments for the reviewers here

### CODE REVIEW

**Review by jan-petr — CHANGES_REQUESTED** [review]
Can you change .mat back to .nii.mat - see Whatsapp.

**Review by HenkMutsaerts — CHANGES_REQUESTED** [review]
the `.nii.mat` -> `.mat` etension renaming is wrong, the filename renaming is nice

**Review by jan-petr — APPROVED** [review]
I fixed the extensions. So all should be good now.

**Review by HenkMutsaerts — APPROVED** [review]
Ensure that we tested the new atlases/names in the population module

**Pull request merged**
